---
title: "SELE analysis"
author: "Tim N"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
source("../../global_in/general_scripts.R")
```

```{r}
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
manual_curation <- read.csv("../../manual_cluster_analysis/manual_curation.csv")
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
samp_dat <- data.table::fread("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```

```{r}
manual_curation_test <- manual_curation %>%
    mutate(SELE = str_detect(genes, "SELE"),
           CHI3L1  = str_detect(genes, "CHI3L1"))


chi_res_1 <- chisq.test(manual_curation_test$ischemic_sig, manual_curation_test$SELE)
chi_res_1$observed
chi_res_1$expected


chi_res <- chisq.test(manual_curation_test$CHI3L1, manual_curation_test$SELE)
chi_res$observed
chi_res$expected

sele_vs_chi <- manual_curation_test %>%
    filter(str_detect(label, "_[:digit:]"),
           SELE == TRUE | CHI3L1 == TRUE)

```
See what SELE does across tissues
```{r}
SELE_dat <- GenesFromTissues(genes_of_int = c("SELE", "CD34", "PECAM1", "VCAM1", "CHI3L1", "VWF", "IL6"),
                 key_dat = key_dat,vst_location = "../../Setup Code/output/",
                 run_all_available = T) %>%
    left_join(., phen_dat) %>%
    left_join(., samp_dat)


ggplot(SELE_dat, aes(SELE, PECAM1, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(SELE, CD34, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(SELE, VCAM1, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(SELE, CHI3L1, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(CD34, PECAM1, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(SELE, VWF, color = tissue)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(PECAM1, VWF, color = IL6)) +
    geom_point() +
    theme(legend.position = "bottom")

ggplot(SELE_dat, aes(IL6, SELE, color = as.factor(MHHTN))) +
    geom_point() +
    theme(legend.position = "bottom")




sele_pecam_cor_out <- NULL
for (cur_tiss in unique(SELE_dat$tissue)) {
    tiss_ind = SELE_dat$tissue %in% cur_tiss
    if (sum(is.na(SELE_dat[tiss_ind, "SELE"])) >0) {
        next()
    }
    res_out <- cor.test(SELE_dat[tiss_ind, "SELE"], SELE_dat[tiss_ind, "PECAM1"])
    res_tidy <- cbind(cur_tiss, broom::tidy(res_out))
    sele_pecam_cor_out <- rbind(sele_pecam_cor_out, res_tidy)
}


sele_cd34_cor_out <- NULL
for (cur_tiss in unique(SELE_dat$tissue)) {
    tiss_ind = SELE_dat$tissue %in% cur_tiss
    if (sum(is.na(SELE_dat[tiss_ind, "SELE"])) >0) {
        next()
    }
    res_out <- cor.test(SELE_dat[tiss_ind, "SELE"], SELE_dat[tiss_ind, "CD34"])
    res_tidy <- cbind(cur_tiss, broom::tidy(res_out))
    sele_cd34_cor_out <- rbind(sele_cd34_cor_out, res_tidy)
}

sele_VCAM1_cor_out <- NULL
for (cur_tiss in unique(SELE_dat$tissue)) {
    tiss_ind = SELE_dat$tissue %in% cur_tiss
    if (sum(is.na(SELE_dat[tiss_ind, "SELE"])) >0) {
        next()
    }
    res_out <- cor.test(SELE_dat[tiss_ind, "SELE"], SELE_dat[tiss_ind, "VCAM1"])
    res_tidy <- cbind(cur_tiss, broom::tidy(res_out))
    sele_VCAM1_cor_out <- rbind(sele_VCAM1_cor_out, res_tidy)
}

SELE_dat <- mutate(SELE_dat,
                   DTHHRDY_factor = factor(DTHHRDY, levels = c(1,2,3,4,0)))

putamen_dat <- SELE_dat %>%
    filter(tissue == "brain_spinal_cord__cervical_c_1")

ggplot(putamen_dat,aes(MHBRNPH, SELE, color = factor(DTHHRDY))) +
    geom_point()
ggplot(putamen_dat,aes(factor(DTHHRDY), SELE)) +
    ggforce::geom_sina()
```
Try some linear mixed models
```{r}
model_1 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH + AGE + SEX + (1|tissue) + (1|SUBJID), data = SELE_dat)

model_2 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH + AGE + SEX + PECAM1 + (1|tissue) + (1|SUBJID), data = SELE_dat)

model_3 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH * PECAM1 + AGE + SEX  + (1|tissue) + (1|SUBJID), data = SELE_dat)

model_4 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH  + SEX + PECAM1 + AGE * tissue + (1|SUBJID), data = SELE_dat)

model_5 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH  + SEX  + AGE * tissue * PECAM1 + (1|SUBJID), data = SELE_dat)

model_6 <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH  + SEX  + AGE:tissue + tissue:PECAM1 + PECAM1 + tissue + AGE + (1|SUBJID), data = SELE_dat)

model_6_no_int <- lmer(SELE ~ DTHHRDY_factor + SMTSISCH  + SEX  + AGE:tissue + tissue:PECAM1 + PECAM1 + tissue + AGE + (1|SUBJID) -1 , data = SELE_dat)

summary(model_1)

summary(model_2)

summary(model_3)

summary(model_4)

summary(model_5)

summary(model_6)

summary(model_6_no_int)
anova(model_1, model_2)
## Include PECAM
anova(model_2, model_3)
## THe interaction factor makes the model worse
anova(model_2, model_4)
## Making tissue a factor and making it interact with age makes the model better
anova(model_4, model_5)
## Making tissue also interact with PECAM also improves the value of the tissue
anova(model_5, model_6)
## I think I will stick with model 6 as it outperforms model 5
## in AIC and BIC with only a minimal increase in reduction of
## variance

current_model_summary <- summary(model_6)

SELE_dat %>%
    filter(tissue == "adipose_subcutaneous") %>%
    ggplot(., aes(AGE, SELE)) +
    geom_point() +
    geom_smooth(method = "lm")

SELE_dat %>%
    ggplot(., aes(AGE, SELE, color = tissue)) +
    geom_point() +
    geom_smooth(method = "lm") +
    theme(legend.position = "none")

SELE_dat %>%
    ggplot(., aes(PECAM1, SELE, color = tissue)) +
    geom_point() +
    geom_smooth(method = "lm") +
    theme(legend.position = "none")

SELE_dat %>%
    filter(tissue == "adipose_subcutaneous") %>%
    ggplot(., aes(factor(MHPSBLDCLT), SELE)) +
    ggforce::geom_sina()


```

See if correlations between tissues and PECAM
```{r}
p_val_ind <- (current_model_summary$coefficients[,"Pr(>|t|)"]) < 0.05
sig_coefficients <- current_model_summary$coefficients[p_val_ind,]

```
New idea make a model for each tissue and see where age or PECAM1 is sig and in which direction.
```{r}

lm_outs <- NULL
summary_out <- list()
for (cur_tiss in unique(SELE_dat$tissue)) {
    cur_dat <- filter(SELE_dat, tissue == cur_tiss)
    if (sum(is.na(cur_dat$SELE)) > 1) {
        next()
    }
    cur_model <- lm(SELE ~ DTHHRDY_factor + SMTSISCH  + SEX + VWF + AGE,
       data = cur_dat)
    cur_summ <- summary(cur_model)
    summary_out[[cur_tiss]] <- cur_summ
    ## Get a row that says if something either positively or negatively correlated
    sig_ind <- cur_summ$coefficients[,"Pr(>|t|)"] < 0.05
    direction_estimate <- ifelse(cur_summ$coefficients[,"Estimate"] >= 0,
                                 "pos_corr", "neg_corr")
    to_be_row <- rep("not_sig", length(sig_ind))
    names(to_be_row) <- names(sig_ind)
    to_be_row[sig_ind] <- direction_estimate[sig_ind]
    sig_row <- as.data.frame(t(as.data.frame(to_be_row)))
    sig_prebind <- cbind(cur_tiss, sig_row)
    
    
    ## Sex tissues
    if (length(unique(cur_dat$SEX))== 1) {
        sig_prebind <- mutate(sig_prebind, SEX = NA) %>%
            select(colnames(lm_outs))
    }
    lm_outs <- rbind(lm_outs, sig_prebind)
}


```



Sele correlation plot
```{r}
SELE_cor <- SELE_dat %>%
    filter(!(tissue %in% c("spleen", "whole_blood"))) %>%
    select(SUBJID, SELE, tissue) %>%
    pivot_wider(names_from = tissue, values_from = SELE) %>%
    column_to_rownames("SUBJID") %>%
    cor(., use = "pairwise.complete.obs")
breaksList = seq(-1,1,by=.01)
pheatmap(SELE_cor,
          breaks = breaksList,
                        color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(breaksList)))

```

Across tissue correlation distribution
```{r}
# n_sample_genes <- 1
# n_boostraps <- 100
# all_genes <- unique(unlist(cluster_list))
# distribution_table <- NULL
# for (cur_ind in seq(n_boostraps)) {
#     rand_names <- sample(all_genes, n_sample_genes)
#     
#     ## Get the Genes
#     rand_genes <- GenesFromTissues(genes_of_int = rand_names, key_dat = key_dat,
#                      vst_location = "../../Setup Code/output/",
#                      run_all_available = T)
#     
#     
#     rand_genes$zscore <- NewZScoreMaker(rand_genes)
#     
#     ## Try to make a correlation matrix
#     pre_cor_mat <- select(rand_genes, SUBJID, zscore, tissue) %>%
#         pivot_wider(names_from = tissue, values_from = zscore) %>%
#         column_to_rownames(var = "SUBJID")
#     
#     cor_mat <- cor(pre_cor_mat, use = "pairwise.complete.obs")
#     
# 
# }
```

Top and bottom SELE
```{r}
SELE_dat %>%
    filter(tissue == "lung") %>%
    ggplot(., aes(PECAM1, SELE)) +
    geom_point()
```
Marc Suggested plot
```{r}
require(viridis)
require(patchwork)
SELE_associated_genes <- head(CommonGenes("SELE", cluster_list = cluster_list,x_clust = F), 11)
how_many_SELE <- SELE_associated_genes$Freq[1]
SELE_associated_genes <- SELE_associated_genes[-1,]
SELE_associated_genes$common_genes <- factor(SELE_associated_genes$final_vect,
                                             levels = rev(SELE_associated_genes$final_vect))
sele_plot <- ggplot(SELE_associated_genes, aes(common_genes, Freq)) +
    geom_col(fill = viridis::inferno(4)[2]) +
    geom_text(aes(label = Freq), position=position_dodge(width=0.9),hjust = -.3) +
    coord_flip() +
    theme_minimal() +
    labs(title = "Genes that cluster with SELE",
         subtitle = paste("Out of", how_many_SELE,"clusters"),
         y = "N of clusters with SELE",
         x = "")



PLA2G2A_associated_genes <- head(CommonGenes("PLA2G2A", cluster_list = cluster_list,x_clust = F), 10)
PLA2G2A_associated_genes$common_genes <- factor(PLA2G2A_associated_genes$final_vect,
                                             levels = rev(PLA2G2A_associated_genes$final_vect))
how_many_PLA2G2A <- PLA2G2A_associated_genes$Freq[1]
PLA2G2A_associated_genes <- PLA2G2A_associated_genes[-1,]
plag_plot <- ggplot(PLA2G2A_associated_genes, aes(common_genes, Freq)) +
    geom_col(fill = viridis::inferno(4)[3]) +
    geom_text(aes(label = Freq), position=position_dodge(width=0.9),hjust = 1.3) +
    coord_flip()  +
    scale_y_reverse() +
    scale_x_discrete(position = "top") +
    theme_minimal() +
    labs(title = "Genes that cluster with PLA2G2A",
         subtitle = paste("Out of", how_many_PLA2G2A,"clusters"),
         y = "N of clusters with PLA2G2A",
         x = "")

joined_plot <- plag_plot + sele_plot

pdf(file = "data_out/sele_pla2g2a_plot.pdf", width = 12, height = 5)
joined_plot
dev.off()
```

