---
title: "Set up analysis code"
author: "Tim Nieuwenhuis"
date: "3/9/2021"
output: html_document
---

## Purpose
The purpose of this rmd file is to generate various datasets and rda's used in this analysis. Many of these files and their results can end up being quite large so it is suggested you have 16 gb of ram on the computer you decide to run this on.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R.utils)
library(tidyverse)
library(DESeq2)
library(data.table)
```

Generate gtex counts RDA

```{r}
### Download the required files from GTEx portal 
## Get reaadcounts of genes
download.file("https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz",
              destfile = "downloaded_input/gtex_read_counts.gct.gz")
gunzip("downloaded_input/gtex_read_counts.gct.gz",remove = T)
## Get sample data
stab <- fread("https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt",
              data.table = FALSE)

## Load in read counts and make gene object
dat <- fread("downloaded_input/gtex_read_counts.gct",data.table = FALSE)
gtab <- dat[,1:2]
colnames(gtab) <- c("gene_id", "gene_name")
dat <- dat[,-1:-2]
rownames(dat) <- gtab$gene_id

## Remove unused samples
stab <- dplyr::filter(.data = stab, SAMPID %in% colnames(dat))
## Make sure samples are in teh same orer as the gtab
ncol(dat) == sum(stab$SAMPID == colnames(dat))

## Save data
save(dat, gtab, stab, file = "output/gtex-gene-counts-v8.rda")
```

Generate rda files used for pca checking
```{r}
load("output/gtex-gene-counts-v8.rda")

## All tissues ran so far are commented out below
# tissue_list = c("lung",
#                 "artery_coronary",
#                 "kidney_cortex",
#                 "skin_sun_exposed",
#                 "prostate",
#                 "brain_spinal_cord__cervical_c_1",
#                 "colon_sigmoid",
#                 "whole_blood","adipose_subcutaneous",
                # "adipose_visceral__omentum",
                # "artery_aorta",
                # "artery_tibial",
                # "artery_coronary",
                # "breast_mammary_tissue",
                # "adrenal_gland",
                # "colon_transverse",
                # "minor_salivary_gland",
                # "skin_not_sun_exposed__suprapubic",
                # "nerve_tibial",
#                   "liver",
                #   "heart_atrial_appendage",
#                   "spleen",
                #   "pancreas",
#                   "pituitary"
                # "heart_left_ventricle")
# tissue_names = c("Lung",
#                  "Artery - Coronary",
#                  "Kidney - Cortex",
#                  "Skin - Sun Exposed (Lower leg)",
#                  "Prostate",
#                  "Brain - Spinal cord (cervical c-1)",
#                  "Colon - Sigmoid",
#                  "Whole Blood","Adipose - Subcutaneous",
                 # "Adipose - Visceral (Omentum)",
                 # "Artery - Aorta",
                 # "Artery - Tibial",
                 # "Artery - Coronary",
                 # "Breast - Mammary Tissue",
                 # "Adrenal Gland",
                 # "Colon - Transverse",
                 # "Minor Salivary Gland",
                 # "Skin - Not Sun Exposed (Suprapubic)",
                 # "Nerve - Tibial"
                # "Liver",
                # "Heart - Atrial Appendage"
                # "Spleen",
                # "Pancreas",
                # "Pituitary"
                # "Heart - Left Ventricle")


tissue_list = c("heart_left_ventricle")
tissue_names = c("Heart - Left Ventricle")

for (j in seq(length(tissue_list))) {
    cur_tiss <- tissue_list[j]
    cur_name <- tissue_names[j]
    
    ind <- which(stab$SMTSD%in% cur_name)

    filt_dat <- dat[,ind]
    filt_stab <- stab[ind,]

    des_dat <- DESeqDataSetFromMatrix(countData = filt_dat,
                               colData = filt_stab,
                               design = ~ 1)
    ## We used varianceStabilizingTransformation() but use vst to save time
    vst_dat <- DESeq2::varianceStabilizingTransformation(des_dat)
    m <- rowMeans(assay(vst_dat))
    ## select clearly expressed genes
    ind <- which(m>5)
    gtabMeanFiltered <- gtab[ind,]
    generalVSDMeanFiltered <- vst_dat[ind,]
    #assign(paste0(cur_tiss,"VSDMeanFiltered"), generalVSDMeanFiltered)
    
    save(gtabMeanFiltered, generalVSDMeanFiltered,
         vst_dat, gtab,
         file=paste0("output/",
                     cur_tiss,"-vsd-mean-filtered.rda"))
    
}

```

```{r}
sink(file = paste0('run_history/set_up_code_session_info_', Sys.Date(), ".txt"),
     type = "output")
sessionInfo()
sink()
```

