---
title: "Cluster seperation methods"
author: "Tim Nieuwenhuis"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(clusterExperiment)
library(DESeq2)
library(SuppDists)
```

MCall Functions
```{r}
mcall_cluster_generator <- function(cor_out,
                             cluster_breaker = FALSE){
    vsdHighVar <- cor_out[["high_var_genes"]]
    gcor <- cor_out[['correlation_matrix']]
    ngene <- nrow(vsdHighVar)
    nsamp <- ncol(vsdHighVar)
    #tauCrit_old <- round(-qrank(0.01/((ngene^2)-ngene)/2, nsamp, index="kendall", approx = "gaussian")$Cq, 2)
    tauCrit <- round(qKendall(0.01/((ngene^2)-ngene)/2, nsamp, lower.tail = F), 2)
    
    ## cluster based on absolute correlation distance
    dendo <- hclust(d=as.dist(1-abs(gcor)), method = "average")
    
    ## clean up heatmap to focus on interesting gene clusters
    clusts <- cutree(dendo, h=1-tauCrit)
    tabclusts <- table(clusts)
    ind <- which(tabclusts >= 6) #arbitrary
    clusts[!(clusts %in% names(tabclusts)[ind])] <- 0
    ntmp <- names(clusts)
    clusts <- as.numeric(as.factor(clusts))-1
    names(clusts) <- ntmp
    
    ### Here is where we will build out the second cluster feature maker
    ## We need to loop through each cluster and subset it out 
    ### BEGINNING OF CLUSTER BREAKER ###
    if (cluster_breaker == TRUE) {
    for (each_clust in unique(clusts)[-1]) {
      ## Subset out clusters to test each of them
      genes <- names(clusts[clusts %in% each_clust])
      sub_clust <- (gcor[genes,genes])
      cur_clust_mean <- mean(abs(sub_clust))
      ## Create a threshold that determine if we slice a cluster or not
      break_down_threshold <- quantile(abs(gcor), .80)
      if (cur_clust_mean < break_down_threshold) {
        sub_dendo <- hclust(d=as.dist(1-abs(sub_clust)), method = "average")
        cur_thresh <- quantile(abs(sub_clust), .85) ## Quantile value is arb
        cur_min_corr <- 1
        starting_cut <- 0
        
        while (cur_thresh <= cur_min_corr) {
          clusts_sub <- cutree(sub_dendo, h = starting_cut)
          corr_vals <- sapply(unique(clusts_sub), FUN = function(x){
              cur_clust <- clusts_sub[clusts_sub == x]
              cur_genes <- names(cur_clust)
              mean(abs(sub_clust[cur_genes,cur_genes]))
            })
          cur_min_corr = min(corr_vals)
          starting_cut = starting_cut + 0.001
        }
        all_clusts <- table(clusts_sub)
        ind <- all_clusts > 6
        clusts_filt <- all_clusts[ind]
        clusts_sub[!(clusts_sub %in% names(clusts_filt))] <- 0
        ## Remove current clust from clusts
        clusts <- clusts[!(clusts == each_clust)]
        ## Rename new old clusters
        no_clust_only <- clusts_sub[clusts_sub == 0]
        true_clust_only <- clusts_sub[clusts_sub != 0]
        new_nums <- seq(max(clusts) + 1, max(clusts) + length(unique(true_clust_only)))
        for (ind in seq(length(unique(true_clust_only)))) {
          true_clust_only[true_clust_only == unique(true_clust_only)[ind]] <- new_nums[ind]
        }
        clusts_sub <- c(no_clust_only, true_clust_only)
        ## Throw 0 clusts in with the rest of the 0s
        clusts <- c(clusts, clusts_sub)
      }
      
    }
    ## Rename clusters here
    new_nums <- seq(0, length(unique(clusts)) - 1)
    for (ind in seq(length(unique(clusts)))) {
      clusts[clusts == unique(clusts)[ind]] <- new_nums[ind]
    }
    }
    ### END OF CLUSTER BREAKER ###
    #Naming clusters based on their clust values
    #Very manual process
    n <- length(table(clusts))
    cnames <- rep("", length(clusts))
    
    #Tim for loop
    for (clst in 1:(n)){
      cnames[clusts==clst] <- LETTERS[clst]
    }
    
    anno = data.frame("cluster"=factor(cnames))
    rownames(anno) = names(clusts)
    
    out_list <- cor_out
    out_list[["anno_df"]] <- anno
    out_list[["cluster_names"]] <- cnames
    out_list[["clust_num"]] <- n
    out_list[["dendogram"]] <- dendo
    
    out_list
}


mccall_analysis_corr_step <- function(tissue,
                             path_to_files,
                             variance_type,
                             variance_value,
                             correlation = "kendall"){
    load(paste0(path_to_files,tissue,"-vsd-mean-filtered.rda"))
    vsdMeanFiltered <- generalVSDMeanFiltered
    v <- apply(assay(vsdMeanFiltered),1,var)
    if (variance_type == "manual") {
      variance_thresh <- variance_value
      ind <- which(v > variance_thresh)
    } else{
      variance_thresh <- quantile(v, variance_value)
      ind <- which(v > variance_thresh)
      variance_thresh <- round(variance_thresh,2)
    }
    
    

    #creating highvar subset
    vsdHighVar <- assay(vsdMeanFiltered)[ind,]
    rownames(vsdHighVar) <- gtabMeanFiltered$gene_name[ind]
    colnames(vsdHighVar) <- vsdMeanFiltered$SAMPID
    #Removing duplicated genes, Tim code
    dim(vsdHighVar)
    vsdHighVar <-  vsdHighVar[!(duplicated(rownames(vsdHighVar))),]
    dim(vsdHighVar)
    vsdHighVarCentered <- vsdHighVar - rowMeans(vsdHighVar)
    
    ## correlation between high variance genes
    library("pheatmap")
    library("RColorBrewer")
    

    
    #Gcor is correlations between each genes
    gcor <- cor(t(vsdHighVar), method= correlation)
    out_list <- list()
    out_list[["correlation_matrix"]] <- gcor
    out_list[["high_var_genes"]] <- vsdHighVar
    out_list[["high_var_centered"]] <- vsdHighVarCentered
    out_list[["tissue"]] <- tissue
    out_list[["correlation"]] <- correlation
    out_list[["var_thresh"]] <- variance_thresh
    out_list
    
}


sub_cluster_maker <- function(clust_initial){
    
    cnames <- clust_initial$cluster_names
    anno <- clust_initial$anno_df
    gcor <- clust_initial$correlation_matrix
    vsdHighVar <- clust_initial[["high_var_genes"]]
    gclusts <- matrix("", nrow=max(table(cnames)), ncol=length(table(cnames)))
    colnames(gclusts) <- levels(anno$cluster)
    for(k in 1:length(table(cnames))){
          tmp <- colnames(gclusts)[k]
          gclusts[1:sum(cnames==tmp), k] <- rownames(gcor)[cnames==tmp]
        }
        
    #Sub clusters code! Now annotated
    for (column in LETTERS[1:(length(unique(cnames)) -1 )]) {
      #Pull out the first column
      test_col <- gclusts[,column]
      first_gene <- test_col[1]
      #Make an index to subset gcor to just a single clusters
      ind <- which(rownames(gcor) %in% test_col)
      sub_cor <- gcor[ind,ind]
      #Test if the cluster has any negatively correlating genes
      ## This doesn't work let me try a new method generating a new dendo
      ind2 <- sub_cor[,first_gene] < 0
      #If there are negatively correlating genes...
      if (sum(ind2) > 0) {
        dendo_sub <- hclust(d=as.dist(1-(sub_cor)), method = "average")
    
        ## clean up heatmap to focus on interesting gene clusters
        sub_clusts <- cutree(dendo_sub,k = 2)
          
        #generate sub cluster 1
        sub_1 <- names(sub_clusts)[sub_clusts == 1]
        #Subcluster 2
        sub_2 <- names(sub_clusts)[sub_clusts == 2]
        #Remover old column to replace with new columns
        gclusts <- as.matrix(gclusts[,!(colnames(gclusts) == column)])
        #Make a single matrix of same rows as gclusts, one for each sub-cluster. 
        matrix_1  <- as.matrix(c(sub_1 ,rep("", nrow(gclusts) - length(sub_1))), )
        colnames(matrix_1) <- paste0(column,"-1")
        matrix_2  <- as.matrix(c(sub_2 ,rep("", nrow(gclusts) - length(sub_2))), )
        colnames(matrix_2) <- paste0(column,"-2")
        #Add subclusters to gclusts
        gclusts <-   cbind(gclusts, matrix_1, matrix_2)
    
        }
      
    }

    #Realphebatize columns for sake of beauty 
    gclusts <- gclusts[,order(colnames(gclusts))]
    
    ## Stratify cluster inclusion
    ind <- which(rownames(vsdHighVar) %in% rownames(gcor)[cnames != ""])
    vsdHighVarClust <- clust_initial$high_var_genes[ind,]
    vsdHighVarCenteredClust <- clust_initial$high_var_centered[ind,]
    vsdHighVarNoise <- clust_initial$high_var_genes[-ind,]
    
    
    clust_initial[["cluster_genes"]] <- gclusts
    clust_initial[["high_var_clusters"]] <- vsdHighVarClust
    clust_initial[["high_var_clust_cent"]] <- vsdHighVarCenteredClust
    clust_initial[["high_var_noise"]] <- vsdHighVarNoise
    clust_initial
}


mccall_profile_maker <- function(sub_clust_out){
    gclusts <- sub_clust_out$cluster_genes
    vsdHighVarCenteredClust <- sub_clust_out$high_var_clust_cent
    ## extract expression for each cluster, convert to zscores, and summarize profile
    clusterProfiles <- matrix(nrow=ncol(vsdHighVarCenteredClust), ncol=(ncol(gclusts) - 1))
    for(k in 1:ncol(clusterProfiles)){
      # ind <- which(cnamesClust == LETTERS[k])
      
      #New code picks from gclusts
      ind <- rownames(vsdHighVarCenteredClust) %in%  gclusts[,1 + k]
      
      #FOr normal clusters 
      if (length(unique(gclusts[,1 + k])) != 2) {
        
        etmp <- vsdHighVarCenteredClust[ind,]
        ztmp <- etmp / apply(etmp, 1, mad)
        #Below removes inf values
        ztmp <- ztmp[is.finite(rowSums(ztmp)),]
        
        clusterProfiles[,k] <- colMeans(ztmp)
      } else {
        #For single genes such as XIST
        etmp <- vsdHighVarCenteredClust[ind,]
        clusterProfiles[,k] <- etmp
        
        
      }
      
      
      
      
    }
    rownames(clusterProfiles) <- colnames(vsdHighVarCenteredClust)
    colnames(clusterProfiles) <- colnames((gclusts))[-1]
    sub_clust_out[["sample_profiles"]] <- clusterProfiles
    sub_clust_out
}

```



Generate data
```{r}
quant_dat <- mccall_analysis_corr_step("lung",
                              path_to_files = "../../Setup Code/output/",
                              variance_type = "quantile",
                              variance_value = .98,
                              correlation = "spearman")
quant_dat <- mcall_cluster_generator(quant_dat)
quant_dat <- sub_cluster_maker(quant_dat)
quant_dat <- mccall_profile_maker(quant_dat)


```

```{r}
B_genes <- c(quant_dat$cluster_genes[,3], quant_dat$cluster_genes[,4])
B_genes <- B_genes[B_genes != ""]

gcor <- quant_dat$correlation_matrix

b_cor <- gcor[B_genes, B_genes]

multi_clust_out_b_clust <-  RSEC(abs(b_cor),
                         isCount = FALSE,
                         reduceMethod = "none",
                         k0s = 1,
                         alphas=c(0.1, 0.2),
                         random.seed = 123)

tableClusters(multi_clust_out_b_clust)


defaultMar<-par("mar")
plotCMar<-c(1.1,8.1,4.1,1.1)
par(mar=plotCMar)
plotClusters(multi_clust_out_b_clust,main="Clusters from RSEC", whichClusters="workflow")

plotCoClustering(multi_clust_out_b_clust,whichClusters=c("mergeClusters","makeConsensus"))



gene_consensus <- clusterMatrix(multi_clust_out_b_clust)[,1]
## There are currently duplicatd names check if these duplicated 
## names all share the same values
for (cur_genes in unique(names(gene_consensus))) {
  name_ind <- names(gene_consensus) %in% cur_genes
  name_ind
}


new_high_var_clusters <- matrix(data = "",
                           nrow =  max(table(gene_consensus)),
                           ncol = length(unique(gene_consensus)))


colnames(new_high_var_clusters) <- (unique(gene_consensus))[order((unique(gene_consensus)))]
for (col_ind in seq(ncol(new_high_var_clusters))) {
    actual_ind <- colnames(new_high_var_clusters)[col_ind]
    cur_genes <- names(gene_consensus[gene_consensus == actual_ind])
    new_col <- c(cur_genes, rep("", nrow(new_high_var_clusters) - length(cur_genes)))
    new_high_var_clusters[,col_ind] <- new_col
}
write.csv(new_high_var_clusters, "clusterExperiment_abs_sub_b_clusters_2.csv", row.names = F)
```

Make a function to use the output from custerExperiment to make a quick heatmap
```{r}
cor_mat <- b_cor
clustExp_out <- multi_clust_out_b_clust
file_save <- FALSE
file_name <- "data_out/b_clust_clustExp_lung.pdf"
cluster_comparer <- function(cor_mat,
                             clustExp_out,
                             file_save = FALSE,
                             file_name){
  ##Get dendo
  dendo <- hclust(d=as.dist(1-abs(cor_mat)), method = "average")
  ## Get coloration
  gene_consensus <- clusterMatrix(clustExp_out)[,1]
  anno <- as.data.frame(gene_consensus)
  colnames(anno) <- "cluster"
  anno_colors <- list("cluster"=c("white",
                                  viridis::viridis(length(unique(gene_consensus)) -1)))
  names(anno_colors$cluster) <- c(-1:max(gene_consensus))[-1:max(gene_consensus) != 0]
  colors <- colorRampPalette( brewer.pal(11, "RdBu")[2:10] )(255)
  brks <- seq(0,2,length=length(colors)+1)
  anno[,1] <- as.factor(anno[,1])
  pheatmap(1-cor_mat, col=colors, breaks=brks,
                cluster_rows=dendo, cluster_col=dendo, 
                legend_breaks=c(2,1.5,1,0.5,0), 
                legend_labels=c("-1.0","-0.5","0","0.5","1.0"),
                fontsize=5, fontsize_row=3, fontsize_col=3,
                
                annotation_col = anno, annotation_row = anno, 
                
                annotation_colors = anno_colors,
                border_color = NA,
                filename=file_name, 
                width=10, height=8)
                             }
```


Generate and understanding of the two clear subclusters
```{r}
ig_ind <- startsWith(rownames(b_cor), "IG")

ig_cor <- b_cor[ig_ind, ig_ind]

dendo <- hclust(d=as.dist(1-abs(b_cor)), method = "average")

ngene <- nrow(b_cor)
nsamp <- ncol(quant_dat$high_var_genes)
tauCrit <- round(qKendall(0.01/((ngene^2)-ngene)/2, nsamp, lower.tail = F), 2)
clusts <- cutree(dendo, h=1-tauCrit)
tabclusts <- table(clusts)

pheatmap(1-b_cor,
                cluster_rows=dendo, cluster_col=dendo, 
                legend_breaks=c(2,1.5,1,0.5,0), 
                legend_labels=c("-1.0","-0.5","0","0.5","1.0"),
                fontsize=5, fontsize_row=3, fontsize_col=3,
                                border_color = NA,
                width=10, height=8)
plot(dendo)
```
Tim hare brained idea
```{r}
## New subcluster idea
## Set an absolute correlation threshold based on quantile of 
## the cluster (or all data)
## Slowly move up cut length and at each move make sure all cluster means are
## > the threshold. Once a cluster is created that breaks the threshold quit
#cur_thresh <- quantile(abs(b_cor), .80)
B_genes <- c(quant_dat$cluster_genes[,3], quant_dat$cluster_genes[,4])
B_genes <- B_genes[B_genes != ""]

gcor <- quant_dat$correlation_matrix

b_cor <- gcor[B_genes, B_genes]
dendo <- hclust(d=as.dist(1-abs(b_cor)), method = "average")


cur_thresh <- quantile(abs(b_cor), .85) ## Quantile value is arb
cur_min_corr <- 1
starting_cut <- 0

while (cur_thresh <= cur_min_corr) {
  clusts <- cutree(dendo, h = starting_cut)
  corr_vals <- sapply(unique(clusts), FUN = function(x){
      cur_clust <- clusts[clusts == x]
      cur_genes <- names(cur_clust)
      mean(abs(b_cor[cur_genes,cur_genes]))
    })
  cur_min_corr = min(corr_vals)
  starting_cut = starting_cut + 0.001
}
all_clusts <- table(clusts)
ind <- all_clusts > 6
clusts_filt <- all_clusts[ind]
clusts[!(clusts %in% names(clusts_filt))] <- 0


filt_clusts <- clusts
cor_mat <- b_cor
file_name <- "data_out/new_cluster_method_bcor_quant.pdf"




cluster_comparer_2 <- function(cor_mat,
                             filt_clusts,
                             file_save = FALSE,
                             file_name){
  ##Get dendo
  dendo <- hclust(d=as.dist(1-abs(cor_mat)), method = "average")
  ## Get coloration
  gene_consensus <- filt_clusts
  anno <- as.data.frame(gene_consensus)
  colnames(anno) <- "cluster"
  anno_colors <- list("cluster"=c("white",
                                  viridis::viridis(length(unique(gene_consensus)) -1)))
  names(anno_colors$cluster) <- c(sort(unique(gene_consensus)))
  colors <- colorRampPalette( brewer.pal(11, "RdBu")[2:10] )(255)
  brks <- seq(0,2,length=length(colors)+1)
  anno[,1] <- as.factor(anno[,1])
  pheatmap(1-cor_mat, col=colors, breaks=brks,
                cluster_rows=dendo, cluster_col=dendo, 
                legend_breaks=c(2,1.5,1,0.5,0), 
                legend_labels=c("-1.0","-0.5","0","0.5","1.0"),
                fontsize=5, fontsize_row=3, fontsize_col=3,
                
                annotation_col = anno, annotation_row = anno, 
                
                annotation_colors = anno_colors,
                border_color = NA,
                filename=file_name, 
                width=10, height=8)
                             }

cluster_comparer_2(b_cor,clusts,file_name = "data_out/new_lung_b_quant_gcor_85.pdf")

```

Hair brain outputs
```{r}
tissue_list = c("lung", "artery_coronary",	"kidney_cortex",
                     "skin_sun_exposed", "prostate")
analysis_list <- list()

for (tissue in tissue_list) {
    
    initial_cor_dat <- mccall_analysis_corr_step(tissue,
                                  path_to_files = "../../Setup Code/output/",
                                  variance_type = "quantile",
                                  variance_value = .98,
                                  correlation = "spearman")
    no_break <- mcall_cluster_generator(initial_cor_dat)
    no_break <- sub_cluster_maker(no_break)
    no_break <- mccall_profile_maker(no_break)
    
    yes_break <- mcall_cluster_generator(initial_cor_dat,
                                         cluster_breaker = TRUE)
    yes_break <- sub_cluster_maker(yes_break)
    yes_break <- mccall_profile_maker(yes_break)
    analysis_list[[paste0(tissue,"_no_break")]] <- no_break
    analysis_list[[paste0(tissue,"_yes_break")]] <- yes_break
}

pdf("data_out/break_vs_no_break_comparisons.pdf", width = 12, height = 10)
for (item in analysis_list) {
  unfiltered_heatmap(item,save_plot = F)
}
dev.off()


just_clusts <- lapply(analysis_list, function(x){
  x[["cluster_genes"]]
})

both_breaks <- just_clusts
only_breaks <- just_clusts[str_detect(names(just_clusts), "yes")]

write.xlsx(both_breaks, "data_out/breaking_comparison_genes.xlsx")
write.xlsx(only_breaks, "data_out/new_clust_method_genes.xlsx")

for_avi <- (analysis_list$kidney_cortex_yes_break$sample_profiles)
write.csv(for_avi, "data_out/names_for_avi.csv")
```




Generate new cluster matrix
```{r}
gene_consensus <- clusterMatrix(multi_clust_out_gene)[,1]
gene_clust_finder <- function(gene_consensus, sel_gene){
    gene_names <- names(gene_consensus)
    ind <- gene_names %in% sel_gene
    cur_clust <- gene_consensus[ind]
    gene_consensus[gene_consensus %in% cur_clust]
}

gene_clust_finder(gene_consensus, "SFTPB")

new_high_var_clusters <- matrix(data = "",
                           nrow =  max(table(gene_consensus)),
                           ncol = length(unique(gene_consensus)))

colnames(new_high_var_clusters) <- (unique(gene_consensus))[order((unique(gene_consensus)))]
for (col_ind in seq(ncol(new_high_var_clusters))) {
    actual_ind <- colnames(new_high_var_clusters)[col_ind]
    cur_genes <- names(gene_consensus[gene_consensus == actual_ind])
    new_col <- c(cur_genes, rep("", nrow(new_high_var_clusters) - length(cur_genes)))
    new_high_var_clusters[,col_ind] <- new_col
}


write.csv(new_high_var_clusters, "clusterExperiment_clusters.csv", row.names = F)
```

```{r}
multi_clust_out_corr <-  RSEC((quant_dat$correlation_matrix),
                         isCount = FALSE,
                         reduceMethod = "none",
                         k0s = 4:8,
                         alphas=c(0.1, 0.2, 0.3),
                         random.seed = 123)

tableClusters(multi_clust_out_corr)


defaultMar<-par("mar")
plotCMar<-c(1.1,8.1,4.1,1.1)
par(mar=plotCMar)
plotClusters(multi_clust_out_corr,main="Clusters from RSEC", whichClusters="workflow")

plotCoClustering(multi_clust_out_corr,whichClusters=c("mergeClusters","makeConsensus"))
```

```{r}
gene_consensus <- clusterMatrix(multi_clust_out_corr)[,1]
new_high_var_clusters <- matrix(data = "",
                           nrow =  max(table(gene_consensus)),
                           ncol = length(unique(gene_consensus)))

colnames(new_high_var_clusters) <- (unique(gene_consensus))[order((unique(gene_consensus)))]
for (col_ind in seq(ncol(new_high_var_clusters))) {
    actual_ind <- colnames(new_high_var_clusters)[col_ind]
    cur_genes <- names(gene_consensus[gene_consensus == actual_ind])
    new_col <- c(cur_genes, rep("", nrow(new_high_var_clusters) - length(cur_genes)))
    new_high_var_clusters[,col_ind] <- new_col
}


write.csv(new_high_var_clusters, "clusterExperiment_correlation.csv", row.names = F)
```


Trying RSEC on all data samples wise
```{r}
multi_clust_out_sample <-  RSEC(quant_dat$high_var_genes,
                         isCount = FALSE,
                         reduceMethod = "none",
                         k0s = 4:8,
                         alphas=c(0.1, 0.2, 0.3),
                         random.seed = 123)

tableClusters(multi_clust_out_sample)


defaultMar<-par("mar")
plotCMar<-c(1.1,8.1,4.1,1.1)
par(mar=plotCMar)
plotClusters(multi_clust_out_sample,main="Clusters from RSEC", whichClusters="workflow")

plotCoClustering(multi_clust_out_sample,whichClusters=c("mergeClusters","makeConsensus"))
```
Multiclust out genes
```{r}
multi_clust_out_gene <-  RSEC(t(quant_dat$high_var_genes),
                         isCount = FALSE,
                         reduceMethod = "none",
                         k0s = 2:5,
                         alphas=c(0.1, 0.2, 0.3),
                         random.seed = 123)

tableClusters(multi_clust_out_gene)


defaultMar<-par("mar")
plotCMar<-c(1.1,8.1,4.1,1.1)
par(mar=plotCMar)
plotClusters(multi_clust_out_gene,main="Clusters from RSEC", whichClusters="workflow")

plotCoClustering(multi_clust_out_gene,whichClusters=c("mergeClusters","makeConsensus"))


multi_clust_out_gene$`GTEX-111CU-0326-SM-5GZXO`


clusterMatrix(multi_clust_out_gene)

pdf("cluster_matrix_output.pdf", width = 12, height = 10)
plotCoClustering(multi_clust_out_gene,whichClusters=c("mergeClusters","makeConsensus"),)
dev.off()
```
Save the current output
```{r}
save(multi_clust_out_gene, multi_clust_out_sample,
     file = "clusteExperiment_test_1.rda")
```
