---
title: "question_maker"
author: "Tim Nieuwenhuis"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DESeq2)
library(tidyverse)
source("../../global_in/general_scripts.R")
```

We think PLAG2A might be related to hardy scale and wish to explore it

```{r}

## Load SUBJ data
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
## Load samp data.
samp_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load common subj_dat
subj_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load keys 
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")


## load manual curation
man_cur <- read.csv("../../manual_cluster_analysis/manual_curation.csv")

```


Find out which cluster have plag2a and find out how many genes are associated
in those clusters
```{r}
clusters_with_pla <- str_detect(man_cur$genes, "PLA2G2A")
pla2g_clusters <- man_cur[clusters_with_pla,]
pla2g_clusters %>% select(label, genes, ischemic_sig) %>%
    mutate(n_genes = str_count(genes, ";") + 1)


```

