---
title: "cluster_correlator"
author: "Tim Nieuwenhuis"
date: "5/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pheatmap)
library(RColorBrewer)
library(SuppDists)
library(reshape2)
#library(stringr)
library(tidyverse)
```
tissue_list
```{r}
tiss_list <- read.csv(file = "../../global_in/general_list_test_v8.txt")[,1]
drop_tiss <- c("cervix_ectocervix", "cervix_endocervix", "bladder","fallopian_tube")
tiss_list <- tiss_list[!(tiss_list %in% drop_tiss)]
```

Load in the cluster data 
```{r}

list_dat <- sapply(tiss_list, function(x){
    ## Go through list to load in files
    load_file <-  paste0("../../MARCC output/variance_genes_kendall/kendall-",
                          x,
                          "-gene-clusters-high-variance.csv")
    new_dat <- read.csv(load_file)
    all_col_names <- colnames(new_dat)
    for (cur_col_name in all_col_names) {
        #cur_col_name <- names(new_dat)[col_ind]
        # if (is.na(cur_col_name)) {
        #     break
        # }
        if (str_detect(cur_col_name, "2")) {
            next
        }
        if(str_detect(cur_col_name, "1")){
            flatten_col_name <- str_replace(cur_col_name, ".1", "")
            col_1 <- new_dat[[paste0(flatten_col_name, ".1")]]
            col_2 <- new_dat[[paste0(flatten_col_name, ".2")]]
            join_col <- append(col_1, col_2)
            join_col <- join_col[join_col != ""]
            join_col <- append(join_col, rep("", length(col_1) - length(join_col)))
            remove_old_ind <- !startsWith(colnames(new_dat), flatten_col_name)
            new_dat <- new_dat[remove_old_ind]
            new_dat <- cbind(new_dat, join_col)
            names(new_dat)[ncol(new_dat)] <- flatten_col_name
            
        }
    }
    ## Reorder colnames
    pre_order <- order(colnames(new_dat))
    order_ind <- pre_order[-length(pre_order)]
    order_ind <- append(1, order_ind)
    new_dat <- new_dat[,order_ind]
    df_list <- NULL
    unclustered_vect <- c()
    
    for (col_ind in seq(ncol(new_dat))) {
        new_col <- new_dat[,col_ind]
        ## Remove non-clustering clusters
        # if (colnames(new_dat)[col_ind] != "X") {
        #   df_list[[colnames(new_dat)[col_ind]]] <- new_col[new_col != ""]  
        # }
        ## Keep non-clustering genes and
        df_list[[colnames(new_dat)[col_ind]]] <- new_col[new_col != ""]  
    }
    return_list <- NULL
    return_list[[x]] <- df_list
})
print("hi")
```
Pull out X genes and collapse genes that negatively correlated
```{r}
unclust_genes <- c()
for (tiss_ind in seq_along(list_dat)) {
    tiss_dat <- list_dat[[tiss_ind]]
    orig_n_col <- ncol(tiss_dat)
    for (col_ind in seq_along(tiss_dat)) {
        col_name <- names(tiss_dat[col_ind])
        if (col_name == "X") {
           unclust_genes <- append(unclust_genes, tiss_dat[[col_ind]]) 
        } 
    }
}
#unclust_genes <- unique(unclust_genes)

unclust_ind <- table(unclust_genes) > quantile(table(unclust_genes), .95)
unclust_genes <- unclust_genes[unclust_ind]
```


Build out correlation matrix
```{r}
## Get all unique genes
unique_genes <- (sort(unique(unlist(list_dat))))
## Make an empty psuedo correlation matrix to fill
pseudo_cor_mat <- matrix(data = 0, nrow = length(unique_genes), ncol = length(unique_genes))
colnames(pseudo_cor_mat) <- unique_genes ; rownames(pseudo_cor_mat) <- unique_genes
## Use gene ran in the loop to prevent repeated calculations
gene_ran <- c()
for (gene in unique_genes) {
    ## Filter list dat to only include clusters the gene is found in
    gene %in% list_dat$adipose_visceral__omentum$B
    to_count <- c()
    for (tissue_ind in seq(length(list_dat))) {
        tissue_list <- list_dat[[tissue_ind]]
        for (cluster_ind in seq(length(tissue_list))) {
        gene_result <- gene %in% tissue_list[[cluster_ind]]
        if (gene_result == TRUE) {
            to_count <- append(to_count, tissue_list[[cluster_ind]]) 
            }
        }
    }
    all_hits <- sort(table(to_count),decreasing = T)
    ## We check against previously ran genes to stop redundancy
    all_hits <- all_hits[!(names(all_hits) %in% gene_ran)]
    ## Fill in the matrix
    for (ind_hit_gene in seq_along(all_hits)) {
        hit_gene <- all_hits[ind_hit_gene]
        pseudo_cor_mat[names(hit_gene), gene] <- hit_gene
        pseudo_cor_mat[gene, names(hit_gene)] <- hit_gene
    }
    gene_ran <- append(gene_ran, gene)
}

pseudo_col_sums <- colSums(pseudo_cor_mat)

pseudo_ind <- pseudo_col_sums > quantile(pseudo_col_sums, .25)


genes_n_clusts <- c()
for (ind in seq(nrow(pseudo_cor_mat))) {
    genes_n_clusts <- append(genes_n_clusts, pseudo_cor_mat[ind,ind])
}

names(genes_n_clusts) <- colnames(pseudo_cor_mat)


genes_n_clusts[names(genes_n_clusts) == "PRSS1"]

quantile(genes_n_clusts, c(.85, .90, .95))
```

```{r}
frequent_ind <- genes_n_clusts > 6
frequent_genes <-  genes_n_clusts[frequent_ind]

top_pseudo <- pseudo_cor_mat[frequent_ind,frequent_ind]
top_pseudo_log <- log2(top_pseudo + 1)

##Make the annoation
anno <- data.frame(rep("Never X", nrow(top_pseudo)), row.names = rownames(top_pseudo))
anno[rownames(anno) %in% unclust_genes,] <- "In X"
colnames(anno) <- "X Clust"
colors <- RColorBrewer::brewer.pal(2, "Set1")
anno_colors <- list("X Clust" = c("Never X" = colors[2], "In X" = colors[1]))
pdf("data_out/inter_cluster_correlation_log.pdf", height = 8, width = 10)
pheatmap(top_pseudo_log,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
          annotation_row = anno,
         annotation_col = anno,
         annotation_colors = anno_colors
         )
dev.off()

pdf("data_out/inter_cluster_correlation.pdf", height = 8, width = 10)
pheatmap(top_pseudo,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno,
         annotation_col = anno,
         annotation_colors = anno_colors
         )
dev.off()



pheat_out <- pheatmap(top_pseudo,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno,
         annotation_col = anno,
         annotation_colors = anno_colors
         )

pheat_out_log <- pheatmap(top_pseudo_log,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno,
         annotation_col = anno,
         annotation_colors = anno_colors
         )

ordered_cluster <- as.data.frame(pheat_out$tree_row$labels[pheat_out$tree_row$order])
colnames(ordered_cluster) <- "genes"
write.csv(ordered_cluster, "data_out/ordered_cluster_out.csv")

ordered_cluster <- as.data.frame(pheat_out_log$tree_row$labels[pheat_out_log$tree_row$order])
colnames(ordered_cluster) <- "genes"
write.csv(ordered_cluster, "data_out/ordered_cluster_log_out.csv")
```
Include eyeball clusters as annotations
```{r}
eyeball_clust <- read.csv("data_in/eyeball_clusters.csv")
anno_2 <- eyeball_clust %>% column_to_rownames("genes") %>% select("cluster")
missing_genes <- rownames(top_pseudo)[!(rownames(top_pseudo) %in% rownames(anno_2))]
missing_genes_df <- data.frame(rep("non_clust",
                                   length(missing_genes)),
                               row.names = missing_genes)
colnames(missing_genes_df) <- colnames(anno_2)
anno_2 <- rbind(anno_2, missing_genes_df)
#anno_colors <- list("X Clust" = c("Never X" = colors[2], "In X" = colors[1]))
anno_names <- unique(anno_2$cluster)
pre_anno_colors <- viridis::viridis_pal()(length(anno_names))
names(pre_anno_colors) <- anno_names
anno_colors <- list("cluster" = pre_anno_colors)
anno_colors$cluster[names(anno_colors$cluster) == "non_clust" ] <- "white"
pdf("data_out/inter_cluster_correlation_eyeball.pdf", height = 8, width = 10)
pheatmap(top_pseudo,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno_2,
         annotation_col = anno_2,
         annotation_colors = anno_colors
         )
dev.off()

```
eyeball attempt 2
```{r}
eyeball_clust_2 <- read.csv("data_in/eyeball_clusters_better.csv")
anno_3 <- eyeball_clust_2 %>% column_to_rownames("genes") %>% select("cluster")
anno_names <- unique(anno_3$cluster)
pre_anno_colors <- sample(viridis::viridis_pal()(length(anno_names)))
names(pre_anno_colors) <- anno_names
anno_colors <- list("cluster" = pre_anno_colors)
anno_colors$cluster[names(anno_colors$cluster) == "no_clust" ] <- "white"
pdf("data_out/inter_cluster_correlation_eyeball_2.pdf", height = 8, width = 10)
pheatmap(top_pseudo,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno_3,
         annotation_col = anno_3,
         annotation_colors = anno_colors
         )
dev.off()


pdf("data_out/inter_cluster_correlation_log_eyeball_2.pdf", height = 8, width = 10)
pheatmap(top_pseudo_log,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno_3,
         annotation_col = anno_3,
         annotation_colors = anno_colors
         )
dev.off()
```

```{r}
eyeball_clust_log <- read.csv("data_in/eyeball_clusters_better_log.csv")
anno_log <- eyeball_clust_log %>% column_to_rownames("genes") %>% select("clusters")
anno_names <- unique(anno_log$clusters)
set.seed(123)
pre_anno_colors <- sample(viridis::viridis_pal()(length(anno_names)))
names(pre_anno_colors) <- anno_names
anno_colors <- list("clusters" = pre_anno_colors)
anno_colors$clusters[names(anno_colors$clusters) == "no_clust" ] <- "white"
pdf("data_out/inter_cluster_correlation_eyeball_log.pdf", height = 8, width = 10)
pheatmap(top_pseudo,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno_log,
         annotation_col = anno_log,
         annotation_colors = anno_colors
         )
dev.off()


pdf("data_out/inter_cluster_correlation_log_eyeball_log.pdf", height = 8, width = 10)
pheatmap(top_pseudo_log,
          fontsize_row = 1.2,
          fontsize_col = 1.2,
         annotation_row = anno_log,
         annotation_col = anno_log,
         annotation_colors = anno_colors
         )
dev.off()
```
Melt eyeballs for marc (lol)

```{r}
dat = eyeball_clust_2[,1:2]
new_col = "cluster"
value_var = "genes"
pseudo_cast <- function(dat, new_col, value_var){

out_list <- list()
for (col_val in unique(dat[[new_col]])) {
    temp_df <- dat[dat[new_col] == col_val,]
    out_list[[col_val]] <- temp_df[[value_var]]
}
 
max_genes <- max(unlist(lapply(out_list, length)))
out_mat <- matrix(nrow=max_genes, ncol = length(out_list))
final_names <- c()
for (cur_col in seq(ncol(out_mat))) {
   cur_name <- names(out_list[cur_col])
   cur_genes <- out_list[[cur_col]]
   make_blanks <- max_genes - length(cur_genes)
   col_genes <- append(cur_genes, rep("", make_blanks))
   out_mat[,cur_col] <- col_genes
   final_names <- append(final_names, cur_name)
}
   colnames(out_mat) <- final_names
   return(out_mat)
}


non_log_cast <- pseudo_cast(eyeball_clust_2[,1:2],new_col = "cluster", "genes")

log_cast <- pseudo_cast(eyeball_clust_log, "clusters","genes")

write.csv(non_log_cast, "data_out/genes_clusters_eyeballed_non_log.csv",row.names = F)
write.csv(log_cast, "data_out/genes_clusters_eyeballed_log.csv",row.names = F)
```



```{r}
cluster_compare_table <- NULL

for (tissue_ind in seq_along(list_dat)) {
    cur_tis <- names(list_dat[tissue_ind])
    cluster_list <- list_dat[[tissue_ind]]
    for (cluster_ind in seq_along(cluster_list)) {
        cluster_names <- names(cluster_list[cluster_ind])
        cluster_genes <- cluster_list[[cluster_ind]]
      cluster_vals <- eyeball_clust_log %>%
                group_by(clusters) %>%
                mutate(in_clust = genes %in% cluster_genes) %>%
                summarize(clusters,percent_overlap = in_clust/n()) %>%
                group_by(clusters) %>%
                arrange(desc(percent_overlap)) %>%
                slice_head( n =1)
     cluster_vals <- as.data.frame(t(cluster_vals))
     colnames(cluster_vals) <- cluster_vals[1,]
     cluster_vals <- cluster_vals[-1,]
     
     ## Add final data
     part_row <- cbind(cur_tis,cluster_names)
     colnames(part_row) <- c("tissue", "cluster")
     temp_row <- cbind(part_row, cluster_vals)
     cluster_compare_table <- rbind(cluster_compare_table, temp_row)
    }
    
}

```

