---
title: "Hypothalamus overlap analysis"
author: "Tim N"
date: "10/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}
library(tidyverse)
library(pheatmap)
source("../../global_in/general_scripts.R")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
```
Read in ovary excel sheet
```{r}
pre_markers <- readxl::read_excel("data_in/41467_2020_18231_MOESM11_ESM.xlsx",
                   sheet = 1)

all_marker_genes <- pre_markers[,-1] %>% pivot_longer(cols = everything(),
                                  names_to = "cluster", values_to = "gene") %>%
    mutate(cluster_factor = factor(cluster),
           human_gene = toupper(gene)) %>%
    filter(!is.na(gene))

### Keeping overlaps for the mean time
#marker_gene_table <- table(all_marker_genes$gene)
#unique_markers <- names(marker_gene_table)[marker_gene_table == 1]
#all_marker_genes <- filter(all_marker_genes, gene %in% unique_markers)
```
Load in clusters
```{r}
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/",x_clust = T)
hypo_dat <- cluster_list$brain_hypothalamus

```

Calculate overlaps
```{r}

dat_out <- NULL
for (cluster_ind in seq_along(hypo_dat)) {
    cur_genes <- hypo_dat[[cluster_ind]]
    temp_dat <- filter(all_marker_genes, human_gene %in% cur_genes)
    new_row <-t(cbind(table(temp_dat$cluster_factor))) %>%
        as.data.frame() %>%
        cbind(.,paste0(cur_genes,collapse = ";"))
    rownames(new_row) <- names(hypo_dat)[cluster_ind]
    dat_out <- rbind(dat_out,new_row)
}
```


```{r}
CommonGenes("HIST2H2BF", cluster_list,x_clust = F)
```

