---
title: "base_Z_score_questions.rmd"
author: "Tim Nieuwenhuis"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../../global_in/general_scripts.R")
```

Select items of interest
```{r}
## Tissue R name
tiss <- "muscle_skeletal"
```

load in data
```{r}

#Load genes and profiles
gene_path <- paste0("../../MARCC output/variance_genes_kendall/kendall-",
                    tiss,"-gene-clusters-high-variance.csv")

clust_genes <- read.csv(gene_path)
prof_path <- paste0("../../MARCC output/variance_profiles_kendall/kendall-",
                    tiss,"-cluster-profiles.csv")
clust_profs <- read.csv(prof_path,row.names = 1)

## Load gene clusters

## Load SUBJ data
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
## Load samp data.
samp_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load common subj_dat
subj_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load keys 
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
```


## Load sample data

Clean and join data


Join_data
```{r}
final_dat <- clust_profs %>% rownames_to_column(var = "SAMPID") %>%
    mutate(SUBJID = GTEx_SAMPID_to_SUBJID(SAMPID)) %>%
    left_join(phen_dat, by = "SUBJID") %>%
    left_join(samp_dat, by = "SAMPID") 

```

Ask questions below
```{r}
ggplot(final_dat, aes(x = SMTSISCH, y = G, color = as.factor(DTHVNT))) +
    geom_point(alpha = .5)

lm_dat <- filter(final_dat, DTHVNT != 99, !is.na(DTHVNT))

summary(lm(G ~ SMTSISCH + DTHVNT + AGE + SEX, data = lm_dat))


ggplot(final_dat, aes(x = SMTSISCH, y = E.2, color = as.factor(DTHVNT))) +
    geom_point(alpha = .5)

ggplot(final_dat, aes(x = SMRIN, y = E.2, color = as.factor(DTHHRDY))) +
    geom_point(alpha = .5)

ggplot(final_dat, aes(x = SMTSISCH, y = E.2, color = as.factor(DTHHRDY))) +
    geom_point(alpha = .5)

ggplot(final_dat, aes(x = SMTSISCH, y = E.1, color = as.factor(DTHHRDY))) +
    geom_point(alpha = .5)

ggplot(final_dat, aes(x = SMTSISCH, y = D, color = as.factor(DTHHRDY))) +
    geom_point(alpha = .5)



```
Finding overlaps between muscle genes and fast and slow twitch genes in our
dataset
```{r}
mouse_twitch_dat <- read.csv("data_in/mouse_skeletal_fast_slow_markers.csv")
mouse_twitch_dat <- mutate(mouse_twitch_dat,
                           twitch = ifelse(average_logFC_scRNA.seq > 0, "fast", "slow"),
                           human_gene = toupper(Gene))
all_clusters<- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
muscle_cluster <- all_clusters$muscle_skeletal

fast_twitch <- filter(mouse_twitch_dat, twitch == "fast")$human_gene
slow_twitch <- filter(mouse_twitch_dat, twitch == "slow")$human_gene

unlist(lapply(muscle_cluster, function(x){ sum(x %in% fast_twitch)}))
unlist(lapply(muscle_cluster, function(x){ sum(x %in% slow_twitch)}))

## No clear fast vs slow twitch, maybe E.2 has more fast twitch and A has more
## slow twitch but that's about it. Let me find out which genes come from which
## clusters though

fast_col <- t(as.data.frame(lapply(
    muscle_cluster, function(x){ paste(x[x %in% fast_twitch],collapse = "; ")})))
slow_col <- t(as.data.frame(lapply(
    muscle_cluster, function(x){ paste(x[x %in% slow_twitch],collapse = "; ")})))
twitch_comparison <- cbind(fast_col,slow_col)
colnames(twitch_comparison) <- c("fast_twitch", "slow_twitch")
```


