unfiltered_heatmap <- function(first_clust_out,
                               save_plot = TRUE,
                               save_file = "",
                               plot_title = NULL,
                               row_col_font = 5,
                               plot_width = 10,
                               plot_height = 8,
                               filter_clust = FALSE){
    ### This plot creates a pheatmap for data generated by the McCall pipeline
    
    n <- first_clust_out$clust_num
    gcor <- first_clust_out$correlation_matrix
    dendo <- first_clust_out$dendogram
    anno <- first_clust_out[["anno_df"]]
    
    if (save_file == "") {
        save_file <- paste0("correlation_heatmap_",
                            first_clust_out$tissue,"_unfilterd.pdf")
    }
    if (filter_clust == FALSE) {
        #anno_colors = list("cluster"=c("white", brewer.pal(n-1, "Spectral")))
        anno_colors = list("cluster"=c("white", viridis::viridis_pal()(n-1)))
        names(anno_colors$cluster) <- c("", LETTERS[1:(n)-1])
        colors <- colorRampPalette( brewer.pal(11, "RdBu")[2:10] )(255)
        brks <- seq(0,2,length=length(colors)+1) } else {
            ## Removing non-clust genes
            n <- n - 1
            anno <- anno %>% filter(cluster != "")
            gcor_ind <- rownames(gcor) %in% rownames(anno)
            gcor <- gcor[gcor_ind, gcor_ind]
            dendo <- hclust(d=as.dist(1-abs(gcor)), method = "average")
            ## Removal complete, this could be moved up to reduce redundancy
            anno_colors = list("cluster"=c(viridis::viridis_pal()(n)))
            names(anno_colors$cluster) <- c(LETTERS[1:(n)])
            colors <- colorRampPalette( brewer.pal(11, "RdBu")[2:10] )(255)
            brks <- seq(0,2,length=length(colors)+1) 
        }
    
    
    if (is.null(plot_title)) {
        plot_title <- paste0(first_clust_out$tissue,"_",
                             first_clust_out$correlation, "_var_",
                             first_clust_out$var_thresh)
    }
    
    
    
    if (save_plot == TRUE) {
        chm <- pheatmap(1-gcor, col=colors, breaks=brks,
                        cluster_rows=dendo, cluster_col=dendo, 
                        legend_breaks=c(2,1.5,1,0.5,0), 
                        legend_labels=c("-1.0","-0.5","0","0.5","1.0"),
                        main=plot_title,
                        fontsize=5, fontsize_row=row_col_font, fontsize_col=row_col_font,
                        
                        annotation_col = anno, annotation_row = anno, 
                        
                        annotation_colors = anno_colors,
                        border_color = NA,
                        filename=save_file, 
                        width=plot_width, height=plot_height)
    } else {
        chm <- pheatmap(1-gcor, col=colors, breaks=brks,
                        cluster_rows=dendo, cluster_col=dendo, 
                        legend_breaks=c(2,1.5,1,0.5,0), 
                        legend_labels=c("-1.0","-0.5","0","0.5","1.0"),
                        main=plot_title,
                        fontsize=5, fontsize_row=row_col_font, fontsize_col=row_col_font,
                        
                        annotation_col = anno, annotation_row = anno, 
                        
                        annotation_colors = anno_colors,
                        border_color = NA,
                        width=plot_width, height=plot_height) 
    }
    
}