---
title: "base_Z_score_questions.rmd"
author: "Tim Nieuwenhuis"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../../global_in/general_scripts.R")
```

Select items of interest
```{r}
## Tissue R name
tiss <- "kidney_cortex"
```

load in data
```{r}

#Load genes and profiles
gene_path <- paste0("../../MARCC output/variance_genes_kendall/kendall-",
                    tiss,"-gene-clusters-high-variance.csv")
clust_genes <- read.csv(gene_path)
prof_path <- paste0("../../MARCC output/variance_profiles_kendall/kendall-",
                    tiss,"-cluster-profiles.csv")
clust_profs <- read.csv(prof_path,row.names = 1)

## Load gene clusters

## Load SUBJ data
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
## Load samp data.
samp_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load common subj_dat
subj_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load keys 
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
```


## Load sample data

Clean and join data


Join_data
```{r}
all_dat <- clust_profs %>% rownames_to_column(var = "SAMPID") %>%
    mutate(SUBJID = GTEx_SAMPID_to_SUBJID(SAMPID)) %>%
    left_join(phen_dat, by = "SUBJID") %>%
    left_join(samp_dat, by = "SAMPID") 

```

Do any of these clusters correlate with kidney disease?
```{r}

disease_dat <- all_dat %>% select(SAMPID, colnames(clust_profs), "MHNEPH", "MHRNLFLR", "MHUREMIA")

cat("nephristis or nephrotic syndrome")
table(disease_dat$MHNEPH)

cat("\n Renale Failure")
table(disease_dat$MHRNLFLR)

cat("\n Uremia")
table(disease_dat$MHUREMIA)
cat("\n We only have people with renal failure")
```


```{r}
plot_dat <- disease_dat %>% select(-MHNEPH, -MHUREMIA) %>%
    mutate(MHRNLFLR = factor(MHRNLFLR)) %>%
    reshape2::melt(id.vars = c("SAMPID", "MHRNLFLR"),value.name = "zscore") 


ggplot(plot_dat, aes(x = MHRNLFLR, y = zscore)) +
    ggforce::geom_sina(alpha = .5) +
    facet_grid(~variable) 

t_table <- NULL
for (cluster in unique(plot_dat$variable)) {
    for_test <- filter(plot_dat, variable == cluster)
    temp_test <- broom::tidy(t.test(zscore ~ MHRNLFLR, for_test ))
    temp_test <- cbind(temp_test, cluster)
    t_table <- rbind(t_table, temp_test)
}

t_table
```

