---
title: "pangloa_analysis"
author: "Tim Nieuwenhuis"
date: "6/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(stringr)
```

Load in the data
```{r}
panglao_dat <- read.table("data_in/PanglaoDB_markers_27_Mar_2020.tsv",
                          sep = "\t", header = TRUE) %>%
    filter(str_detect(species, "Hs"))
key_organs <- read.csv(file = "data_in/ordered_all_tiss_pang_names.csv")
key_genes <- read.csv(file = "../data_out/labels_and_genes.csv")
key_master <- read.csv(file = "../data_out/key_table.csv")


```
Making a general list of organs all tissues will be compared to
```{r}
generalist_organ <- c("Connective tissue", "Immune system", "Epithelium", "Skeletal muscle")
generalist_data <- filter(panglao_dat, organ %in% generalist_organ) %>%
    group_by(organ) %>%
    count(cell.type)

```
Join the data together to make pangloa analysis easier
```{r}

key_organ_prepare <- key_organs %>%
    select(r_names,panglao_match)

dat_for_analysis <- key_master %>% select(label, r_names) %>%
            left_join(key_genes, ., by = "label") %>%
            left_join(key_organ_prepare, by = "r_names") %>%
            select(label, r_names, panglao_match, genes)
```


```{r}
### For each cluster find what percentage of the genes fall into what cell types



## For each gtex tissue
all_tissues <- unique(dat_for_analysis$r_names)
panglao_analysis_list <- list()
for (tiss_ind in seq_along(all_tissues)) {

    cur_tiss <- all_tissues[tiss_ind]
    tiss_df <- filter(dat_for_analysis, r_names %in% cur_tiss)
    ## Select out genes
    temp_pang <- filter(panglao_dat,
                    organ %in%
                        append(generalist_organ, tiss_df$panglao_match))
    ## Make a matrix to fill out with percent cell type
    ## Double the colnames dimensions to include two columns per cell type
    ## proportion 
    temp_matrix <- matrix(nrow = nrow(tiss_df),
                          ncol = 2 * length(unique(temp_pang$cell.type)))
    cur_cell_types <- unique(temp_pang$cell.type)
    ## Make new colnames using sapply
    ## create a vector where we duplicate the names and mark if it is
    ## proportion column or genes
    new_colnames <- sapply(cur_cell_types,function(x){
        reps <- rep(x,2)
        reps[1] <- paste0(reps[1], " proportion")
        reps[2] <- paste0(reps[2], " genes")
        unlist(reps)
    })
    ## Flatten sapply out to fit as colnames
    colnames(temp_matrix) <- as.vector(new_colnames) 
    rownames(temp_matrix) <- tiss_df$label
    for (clust_ind in seq(nrow(tiss_df))) {
        ## Get the current cluster
        cur_row <- tiss_df[clust_ind,]
        ## Break down the genes
        cur_genes <- str_split(cur_row$genes, ";")[[1]]
        ## Loop along vector of cell types to fill out the temp matrix
        for (cell_type_ind in seq_along(cur_cell_types)) {
            ## Get current cell type
            cur_type <- cur_cell_types[cell_type_ind]
            ## Create the odd index which will be used to fill proportion data
            proportion_ind <- seq(1, ncol(temp_matrix), by = 2)[cell_type_ind]
            ## Geene index is even
            gene_ind <-  seq(2, ncol(temp_matrix), by = 2)[cell_type_ind]
            temp_cell <- filter(temp_pang, `cell.type` == cur_type)
            cur_prop <- sum(cur_genes %in%
                    temp_cell$official.gene.symbol)/length(cur_genes)
            ## Get out genes that match and paste them together
            hit_genes <- cur_genes[cur_genes %in%
                    temp_cell$official.gene.symbol]
            hit_genes <- paste0(hit_genes,collapse = "; ")
            ## This code exists to prevent putting true empty characters into the
            ## matrix
            hit_genes <- ifelse(length(hit_genes) == 0, "", hit_genes)
           temp_matrix[clust_ind, proportion_ind] <- round(cur_prop, 4)
           temp_matrix[clust_ind, gene_ind] <- hit_genes
        }
        
    }
    numeric_temp_matrix <- temp_matrix[,str_detect(colnames(temp_matrix),pattern = "proportion")]
    numeric_temp_matrix <- matrix(as.numeric(numeric_temp_matrix),
                                  ncol = ncol(numeric_temp_matrix),
                                  dimnames = list(NULL, colnames(numeric_temp_matrix)))
    ##Begin transformations on the data
    pseudo_proportion <- apply(numeric_temp_matrix, 1, sum)
    
    ## For each generalist get a column
    temp_generalist_matrix <- NULL
    for (general_org in generalist_organ) {
        temp_gen_df <- filter(generalist_data, organ == general_org)
        ## Remove proportion from colnames
        temp_colnames <- str_sub(colnames(numeric_temp_matrix), 1,
                                 nchar(colnames(numeric_temp_matrix)) -11)
        gen_mat <- numeric_temp_matrix[,temp_colnames %in% temp_gen_df$cell.type]
        if (is.vector(gen_mat) == TRUE) {
            temp_generalist_matrix <- cbind(temp_generalist_matrix, gen_mat)
            
        } else{
            sum_vals <- apply(gen_mat, 1, sum)
            temp_generalist_matrix <- cbind(temp_generalist_matrix, sum_vals)
        }
    }
    colnames(temp_generalist_matrix) <- generalist_organ
    
    ## Top tissues in order
     top_cell_types <-  apply(numeric_temp_matrix,1, function(x){
            ## Remove 0s
            x <- x[x!=0]
            ## sort row
            x <- sort(x,decreasing = T)
            ## paste sorted values
            paste0(names(x),collapse = "; ")
        })
    
    ## Sum of genes in cluster
    genes_per_cluster <- str_count(tiss_df$genes, ";") + 1
    
    ## Sum of genes found by panglao in cluster
    char_temp_matrix <- temp_matrix[,str_detect(colnames(temp_matrix),pattern = "gene")]
    n_of_genes_in_pang <-  apply(char_temp_matrix, 1, function(x){
            x <- x[x!=""]
            out <- str_count(x, ";") + str_detect(x, "[:alnum:]") 
            sum(out)
        })
    
    ## Join all the additional columns together
    temp_matrix <- cbind(temp_generalist_matrix,
                         top_cell_types,n_of_genes_in_pang,
                         genes_per_cluster,temp_matrix)
    
    ## Maybe we should reorder columns to the specific pangloa type?
    
    panglao_analysis_list[[cur_tiss]] <- temp_matrix 
    
}

##### Things to add
## [x] total N of genes in a cluster
## [x] A column summing up generalist tissues
## [x] A column with the cell types hit in order of most to least
## [x] Add column behind a cell type match with names of hit genes (multiple column)
## [x] Sum of genes found by panglao per cluster (new single column)


for (ind_to_write in seq_along(panglao_analysis_list)) {
    cur_tiss <- names(panglao_analysis_list)[[ind_to_write]]
    cur_mat <- panglao_analysis_list[[ind_to_write]]
    write.csv(cur_mat, file = paste0("data_out/all_tissue_out/",cur_tiss, "_panglao_analysis.csv"))
}



```

