---
title: "Uterus analysis"
author: "Tim N"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
library(tidyverse)
library(pheatmap)
source("../../global_in/general_scripts.R")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/",x_clust = T)
samp_dat <- data.table::fread("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
```

```{r}

uterus_profile <- ZscoreProfilePuller("uterus", "../../MARCC output/variance_profiles_kendall/")
## Get a correlation matrix of esophagus clusters
all_cor_mat <- ClusterCombinerZscores("uterus",
                       cluster_vect = colnames(uterus_profile$uterus)[-1:-2],
                       uterus_profile,cor_matrix = T)
## Cluster and plot these results to get a clear understanding of esophagus
## relationships
dendo <- hclust(dist(1-abs(all_cor_mat)))
pheatmap((all_cor_mat),cluster_cols = FALSE, cluster_rows = FALSE)
supp_heatmap <- pheatmap((all_cor_mat),cluster_cols = dendo,
                         cluster_rows = dendo,display_numbers = T)
pdf("data_out/uterus_cluster_correlations.pdf", height = 7, width = 9)
supp_heatmap
dev.off()
```

```{r}
ClusterCombinerGenes("uterus", c("G", "M.1", "J.1"), cluster_list)
```

```{r}
joined_dat <- left_join(uterus_profile$uterus, phen_dat) %>%
    left_join(., samp_dat)

menopause_quantiles<- quantile(joined_dat$AGE, c(.25, .75))

young_uterus <- sum(joined_dat$AGE <= menopause_quantiles[1])
older_uterus <-sum(joined_dat$AGE >= menopause_quantiles[2])
nrow(joined_dat) - (young_uterus + older_uterus) 
```
MegaCluster correlations

```{r}
joined_dat$`Mega-cluster Z-score` <- ClusterCombinerZscores("uterus",
                                                            c("G", "M.1", "J.1"),
                                                            uterus_profile)

joined_dat <- mutate(joined_dat, age_quartile = case_when(
    AGE <= menopause_quantiles[1] ~ "bottom quartile",
    AGE >= menopause_quantiles[2] ~ "top quartile")) %>%
    filter(!is.na(age_quartile))

ggplot(joined_dat, aes(age_quartile, `Mega-cluster Z-score`)) +
    ggforce::geom_sina()

lm(`Mega-cluster Z-score` ~ age_quartile +SMTSISCH, data = joined_dat) %>%
    broom::tidy()
```

MegaCluster correlations with A.1

```{r}
joined_dat_A <- left_join(uterus_profile$uterus, phen_dat) %>%
    left_join(., samp_dat)

menopause_quantiles<- quantile(joined_dat_A$AGE, c(.25, .75))

young_uterus <- sum(joined_dat_A$AGE <= menopause_quantiles[1])
older_uterus <-sum(joined_dat_A$AGE >= menopause_quantiles[2])
nrow(joined_dat_A) - (young_uterus + older_uterus) 
```

```{r}
joined_dat_A$`Mega-cluster Z-score` <- ClusterCombinerZscores("uterus",
                                                            c("G", "M.1", "J.1", "A.1"),
                                                            uterus_profile)

joined_dat_A <- mutate(joined_dat_A, age_quartile = case_when(
    AGE <= menopause_quantiles[1] ~ "bottom quartile",
    AGE >= menopause_quantiles[2] ~ "top quartile")) %>%
    filter(!is.na(age_quartile))

ggplot(joined_dat_A, aes(age_quartile, `Mega-cluster Z-score`)) +
    geom_boxplot(outlier.shape = NA) +
    ggforce::geom_sina() +
    theme_classic() +
    labs(x = "Uterine Age Quartiles")
ggsave("data_out/quartile_sina_boxplot_comparisons.pdf")

lm(`Mega-cluster Z-score` ~ age_quartile +SMTSISCH, data = joined_dat_A) %>%
    broom::tidy()
```