---
title: "Where do genes show up tool"
author: "Tim Nieuwenhuis"
date: "6/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../../global_in/general_scripts.R")
```


```{r}
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
```


```{r}

list_dat <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/",
                                 x_clust = FALSE)

```

Genes of interest
```{r}

clusts <- read.csv("../../MARCC output/variance_genes_kendall/kendall-whole_blood-gene-clusters-high-variance.csv")
genes_o_int <- clusts[clusts[,"B.2"] != "", "B.2"]
```

Get genes most commonly shared
```{r}
gene_lapply_out <-  lapply(genes_o_int, function(x){
        res_dat <- lapply(list_dat, function(y){
           ind<- lapply(y, function(z){
                x %in% z
            })
           y[unlist(ind)]
        })
        temp_df <- as.data.frame(table(unlist(res_dat)))
        colnames(temp_df) <- c("genes", x)
        temp_df
    })

for (df_ind in seq_along(gene_lapply_out)) {
    if (df_ind == 1) {
        df_out <- gene_lapply_out[[df_ind]]
    } else{
        df_out <- full_join(df_out, gene_lapply_out[[df_ind]], by = "genes")
    }
}

df_out$most_shared <- column_to_rownames(df_out, "genes") %>% rowSums()

arrange(df_out, desc(most_shared))
```

Get clusters for highest enrichment of gene list
```{r}
cluster_enrichment<- lapply(list_dat, function(x){
    first_lap <- lapply(x, function(y){
        sum(genes_o_int %in% y)
    })
    unlist(first_lap)
})

top_clusters <- sort(unlist(cluster_enrichment),decreasing = T)

top_clusters_filt <- as.data.frame(top_clusters) %>% filter(top_clusters >0)
top_clusters_filt

```
Get the genes from the top clusters
```{r}
clusters_out <- NULL
for (cluster in rownames(head(top_clusters_filt,5))) {
    parts <- unlist(str_split(cluster, "[.]"))
    tissue <- parts[1]
    if (length(parts) == 3) {
        cluster <- paste(parts[2], parts[3],sep = ".")
    } else{
         cluster <- parts[2]
    }
    cur_genes <- list_dat[[tissue]][[cluster]]
    clusters_out[[paste(tissue, cluster, sep = ".")]] <- cur_genes
}
clusters_out
```

