---
title: "Where do genes show up tool"
author: "Tim Nieuwenhuis"
date: "6/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}



list_dat <- sapply(tiss_list, function(x){
    ## Go through list to load in files
    load_file <-  paste0("../MARCC output/variance_genes_kendall/kendall-",
                          x,
                          "-gene-clusters-high-variance.csv")
    new_dat <- read.csv(load_file)
    all_col_names <- colnames(new_dat)
    for (cur_col_name in all_col_names) {
      ## Below code collapses the negatively correlating gene clusters together
        #cur_col_name <- names(new_dat)[col_ind]
        # if (is.na(cur_col_name)) {
        #     break
        # }
        # if (str_detect(cur_col_name, "2")) {
        #     next
        # }
        # if(str_detect(cur_col_name, "1")){
        #     flatten_col_name <- str_replace(cur_col_name, ".1", "")
        #     col_1 <- new_dat[[paste0(flatten_col_name, ".1")]]
        #     col_2 <- new_dat[[paste0(flatten_col_name, ".2")]]
        #     join_col <- append(col_1, col_2)
        #     join_col <- join_col[join_col != ""]
        #     join_col <- append(join_col, rep("", length(col_1) - length(join_col)))
        #     remove_old_ind <- !startsWith(colnames(new_dat), flatten_col_name)
        #     new_dat <- new_dat[remove_old_ind]
        #     new_dat <- cbind(new_dat, join_col)
        #     names(new_dat)[ncol(new_dat)] <- flatten_col_name
        #     
        # }
    }
    ## Reorder colnames
    pre_order <- order(colnames(new_dat))
    order_ind <- pre_order[-length(pre_order)]
    order_ind <- append(1, order_ind)
    new_dat <- new_dat[,order_ind]
    df_list <- NULL
    unclustered_vect <- c()
    
    for (col_ind in seq(ncol(new_dat))) {
        new_col <- new_dat[,col_ind]
        ## Remove non-clustering clusters
        # if (colnames(new_dat)[col_ind] != "X") {
        #   df_list[[colnames(new_dat)[col_ind]]] <- new_col[new_col != ""]  
        # }
        ## Keep non-clustering genes and
        df_list[[colnames(new_dat)[col_ind]]] <- new_col[new_col != ""]  
    }
    return_list <- NULL
    return_list[[x]] <- df_list
    
})
```

Genes of interest
```{r}
genes_o_int <- c("SAA1", "HBA1")
```

Get genes most commonly shared
```{r}
gene_lapply_out <-  lapply(genes_o_int, function(x){
        res_dat <- lapply(list_dat, function(y){
           ind<- lapply(y, function(z){
                x %in% z
            })
           y[unlist(ind)]
        })
        temp_df <- as.data.frame(table(unlist(res_dat)))
        colnames(temp_df) <- c("genes", x)
        temp_df
    })

for (df_ind in seq_along(gene_lapply_out)) {
    if (df_ind == 1) {
        df_out <- gene_lapply_out[[df_ind]]
    } else{
        df_out <- full_join(df_out, gene_lapply_out[[df_ind]], by = "genes")
    }
}

df_out$most_shared <- column_to_rownames(df_out, "genes") %>% rowSums()

arrange(df_out, desc(most_shared))
```

Get clusters for highest enrichment of gene list
```{r}
cluster_enrichment<- lapply(list_dat, function(x){
    first_lap <- lapply(x, function(y){
        sum(genes_o_int %in% y)
    })
    unlist(first_lap)
})

top_clusters <- sort(unlist(cluster_enrichment),decreasing = T)

top_clusters_filt <- as.data.frame(top_clusters) %>% filter(top_clusters >0)

```

Get the genes from the top clusters
```{r}
clusters_out <- NULL
for (cluster in rownames(head(top_clusters_filt,5))) {
    parts <- unlist(str_split(cluster, "[.]"))
    tissue <- parts[1]
    if (length(parts) == 3) {
        cluster <- paste(parts[2], parts[3],sep = ".")
    } else{
         cluster <- parts[2]
    }
    cur_genes <- list_dat[[tissue]][[cluster]]
    clusters_out[[paste(tissue, cluster, sep = ".")]] <- cur_genes
}
clusters_out
```