---
title: "base_Z_score_questions.rmd"
author: "Tim Nieuwenhuis"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../../global_in/general_scripts.R")
```

Select items of interest
```{r}
## Tissue R name
tiss <- "brain_frontal_cortex__ba9"
```

load in data
```{r}

#Load genes and profiles
gene_path <- paste0("../../MARCC output/variance_genes_kendall/kendall-",
                    tiss,"-gene-clusters-high-variance.csv")
clust_genes <- read.csv(gene_path)
prof_path <- paste0("../../MARCC output/variance_profiles_kendall/kendall-",
                    tiss,"-cluster-profiles.csv")
clust_profs <- read.csv(prof_path,row.names = 1)

## Load gene clusters

## Load SUBJ data
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
## Load samp data.
samp_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load common subj_dat
subj_dat <- read.delim("../../global_in/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt", fill=T,
                      stringsAsFactors=FALSE, sep="\t", header=T)
## Load keys 
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
```


## Load sample data

Clean and join data


Join_data
```{r}
final_dat <- clust_profs %>% rownames_to_column(var = "SAMPID") %>%
    mutate(SUBJID = GTEx_SAMPID_to_SUBJIUD(SAMPID)) %>%
    left_join(phen_dat, by = "SUBJID") %>%
    left_join(samp_dat, by = "SAMPID") 

```

Ask questions below
```{r}

cluster_that_has_SAA1 <- colnames(clust_genes)[apply(clust_genes, 2, function(x){"SAA1" %in% x})]

final_dat <- mutate(final_dat, DTHHRDY = factor(DTHHRDY, ordered = TRUE,
                                                      levels = c("1","2","3","4","0")))

ggplot(final_dat, aes_string("DTHHRDY", cluster_that_has_SAA1)) +
    ggforce::geom_sina() +
    labs(title = tiss)

```

```{r}
ggplot(final_dat, aes_string("TRISCHD", cluster_that_has_SAA1)) +
   geom_point() +
    labs(title = tiss)


final_dat <- final_dat %>% 
    mutate(isch_bin = cut(TRISCHD, breaks = quantile(TRISCHD, seq(0,1,.25))),
           dthvnt_fact = as.factor(DTHVNT),
           vnt_bin = cut(DTHVNTD, breaks = quantile(DTHVNTD, seq(0,1,.25), na.rm = T)))

ggplot(final_dat, aes_string("vnt_bin", cluster_that_has_SAA1, color = "dthvnt_fact")) +
   geom_point(alpha = .25) +
    labs(title = tiss,
             x = "Ischemic time in minutes")


ggplot(final_dat, aes_string("TRISCHD", "D.1", color = "dthvnt_fact")) +
   geom_point(alpha = .25) +
    labs(title = tiss,
             x = "Ischemic time in minutes")

ggplot(final_dat, aes_string("isch_bin", cluster_that_has_SAA1, color = "dthvnt_fact")) +
   ggforce::geom_sina(alpha = .25) +
    labs(title = tiss,
         x = "Ischemic time in minutes binned")



ggplot(final_dat, aes_string("dthvnt_fact", "B.2", color = "dthvnt_fact")) +
   ggforce::geom_sina(alpha = .25) +
    labs(title = tiss,
         x = "Ischemic time in minutes binned")
```

```{r}

model_data <- lm(B.2 ~ TRISCHD + dthvnt_fact, data = final_dat)
summary(model_data)

vent_only <- filter(final_dat, dthvnt_fact == "1")

no_vent <-  filter(final_dat, dthvnt_fact == "0")


model_data <- lm(B.2 ~ TRISCHD, data = vent_only)
summary(model_data)


model_data <- lm(B.2 ~ TRISCHD, data = no_vent)
summary(model_data)
```

