---
title: "figure_1c"
author: "Tim N"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.table)
library(viridis)
source("../../global_in/general_scripts.R")
```

## Load phenotype data
```{r}
pheno <- fread("../../global_in/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt") %>%
    mutate(SEX = ifelse(SEX ==1 , "Male", "Female"))
```



Tissue for figure
```{r}
#tiss = "stomach"
## I used the artery in the actual figure, not sure why stoamach was commented out
tiss = "artery_coronary"
```

Find XIST cluster 
```{r}
cur_clusts <- GeneClusterPuller(tiss, "../../MARCC output/variance_genes_kendall/")[[1]]

xist_clust <- unlist(lapply(cur_clusts, function(x){"XIST" %in% x}))
base_sex_clust <- str_sub(names(xist_clust)[xist_clust],1,1)
xist_clust_string <- names(xist_clust)[xist_clust]
```

Pull profiles and join with phenotype
```{r}
cur_profiles <- ZscoreProfilePuller(tiss, "../../MARCC output/variance_profiles_kendall/")[[1]]
for_plot <- left_join(cur_profiles, pheno)
table(for_plot$SEX)
```


```{r}
ggplot(for_plot, aes_string(x = "SEX",
                     y = xist_clust_string,
                     color ="SEX")) +
    ggforce::geom_sina() +
    scale_color_viridis(discrete = T, option = "C",end = .8) +
    theme_classic() +
    theme(legend.position = "none") +
    labs(y = "XIST Z-score")
ggsave("figures_out/figure_1c.pdf", height =5, width = 2)
#ggsave("figures_out/figure_1c_coronary.pdf", height =5, width = 2)
```

