---
title: "Metallothionein"
author: "Tim N"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../../global_in/general_scripts.R")
library(tidyverse)
library(pheatmap)
library(lme4)
library(lmerTest)
## Load key_dat 
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
samp_dat <- data.table::fread("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```

Find all genes in our datas in the family
```{r}
all_clusters <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
all_genes <- unlist(all_clusters)
all_genes_unique <- unique(all_genes)
all_MT <- all_genes_unique[startsWith(all_genes_unique, "MT1")|
                               startsWith(all_genes_unique, "MT2") |
                               startsWith(all_genes_unique, "MT3")]
#write.csv(common_MT_genes, "data_out/MT_in_different_tissues_2.csv")

CommonGenes("MT1G" , all_clusters, x_clust = F)
```
Find body wide MT associations
```{r}
## Get the Genes
MT_genes <- GenesFromTissues(genes_of_int = all_MT, key_dat = key_dat,
                 vst_location = "../../Setup Code/output/",
                 run_all_available = T)


MT_genes$zscore <- NewZScoreMaker(MT_genes)

## Try to make a correlation matrix
pre_cor_mat <- select(MT_genes, SUBJID, zscore, tissue) %>%
    pivot_wider(names_from = tissue, values_from = zscore) %>%
    column_to_rownames(var = "SUBJID")

cor_mat <- cor(pre_cor_mat, use = "pairwise.complete.obs")

breaksList = seq(-1,1,by=.01)

pheatmap(cor_mat,main = "MT-Zscore Pearson Correlations",
         filename = "data_out/MT_gene_correlation_heatmap.pdf",
         height = 8, width = 10,
          breaks = breaksList,
                        color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(breaksList)))

## Average MT genes per organ
mt_n_tiss <- MT_genes %>% select(tissue, starts_with("MT"))

missing_vect <- c()
for (cur_tiss in unique(mt_n_tiss$tissue)) {
    temp_vect <- mt_n_tiss %>% filter(tissue == cur_tiss) %>%
        select(-tissue) %>%
        colSums()
    current_mt_genes <- c(sum(!is.na(temp_vect)))
    names(current_mt_genes) <- cur_tiss
    missing_vect <- append(missing_vect, current_mt_genes)
}
 

## Get most clustering tissues
dendo <- hclust(dist( cor_mat))
plot(dendo)
abline(h=1.4)
clustered_dat <- cutree(dendo,h = 1.6) 
cluster_tissues <- names(clustered_dat)[clustered_dat == 1]
```

Permute across tissue correlations
```{r}
all_genes <- unlist(cluster_list)
new_plots <- list()
breaksList <- seq(-1, 1, by = .01)
for (cur_ind in seq(10)) {
    rand_names <- sample(all_genes, 11)
    
    ## Get the Genes
    rand_genes <- GenesFromTissues(genes_of_int = rand_names, key_dat = key_dat,
                     vst_location = "../../Setup Code/output/",
                     run_all_available = T)
    
    
    rand_genes$zscore <- NewZScoreMaker(rand_genes)
    
    ## Try to make a correlation matrix
    pre_cor_mat <- select(rand_genes, SUBJID, zscore, tissue) %>%
        pivot_wider(names_from = tissue, values_from = zscore) %>%
        column_to_rownames(var = "SUBJID")
    
    cor_mat <- cor(pre_cor_mat, use = "pairwise.complete.obs")
    
   new_plot <- pheatmap(cor_mat,main = paste0(rand_names,collapse = ", "),
                        file = paste0("data_out/random_plots/random_heatmap_", cur_ind, ".pdf"),
                        height = 8, width = 10,
                        breaks = breaksList,
                        color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(breaksList)))
   new_plots[[cur_ind]] <- new_plot
}

```

What does metallo correlate with?
```{r}
MT_all_dat <- left_join(MT_genes, phen_dat) %>%
    mutate(DTHHRDY_factor = factor(DTHHRDY, levels = c(1,2,3,4,0)),
           death_in_hospital = case_when(
               DTHHRDY %in% c(0,3,4) ~ TRUE,
               DTHHRDY %in% c(1,2) ~ FALSE
           ))


MT_all_dat %>%
    filter(tissue == cluster_tissues) %>%
    ggplot(., aes(factor(death_in_hospital), zscore)) +
    ggforce::geom_sina()
## Filter to only clustering tissues
MT_cluster_dat <- filter(MT_all_dat, tissue == cluster_tissues) %>%
    left_join(.,samp_dat)

model <- lmer(zscore ~ death_in_hospital + TRISCHD + SEX + AGE + (1|tissue),
              data = MT_cluster_dat)
summary(model)

## Compare death in hospital to hardy score
MT_model_compare_dat <- filter(MT_cluster_dat, DTHHRDY_factor)

model_death <- lmer(zscore ~ death_in_hospital + TRISCHD + (1|tissue),
              data = MT_cluster_dat)
model_hardy <- lmer(zscore ~ DTHHRDY_factor + TRISCHD + (1|tissue),
              data = MT_cluster_dat)

anova(model_death,model_hardy)


## Compare hospital death and TRISCHD interaction
model_interact <- lmer(zscore ~ death_in_hospital * TRISCHD + SEX + AGE + (1|tissue),
              data = MT_cluster_dat)
summary(model_interact)


anova(model,model_interact)

## Compare TRISCHD to SMTSICHD
model_tiss_isch <- lmer(zscore ~ death_in_hospital + SMTSISCH + SEX + AGE + (1|tissue),
              data = MT_cluster_dat)

summary(model_tiss_isch)
anova(model, model_tiss_isch)

## Two random effects
model_two_effects <- lmer(zscore ~ death_in_hospital + SMTSISCH + SEX + AGE +
                              (1|tissue) + (1|SUBJID),
              data = MT_cluster_dat)
summary(model_two_effects)

anova(model_tiss_isch, model_two_effects)

### Print out model
require(broom.mixed)
tidy_model <- broom.mixed::tidy(model_two_effects)
write.csv(tidy_model,file = "data_out/current_lmer_metallo_model.csv",row.names = F)
```

Find clusters with large MT overlaps and pull their z-score
```{r}
tissues_with_clusters <- ClusterGeneOverlaps(all_MT, cluster_list,only_hits =  T) %>%
    arrange(desc(n_intersect)) %>%
    filter(n_intersect >= 4) %>% rownames_to_column(var="full_name") %>%
    separate(full_name, into = c("tissue", "cluster"), sep = "-")

## Loop through clusters to do analysis?
profile_list <- ZscoreProfilePuller(tissues_with_clusters$tissue,
                                    location = "../../MARCC output/variance_profiles_kendall/")

profile_list<- lapply(profile_list,FUN = function(x) {
    left_join(x, phen_dat) %>% left_join(., samp_dat) %>%
        mutate(DTHHRDY_factor = factor(DTHHRDY, levels = c(1,2,3,4,0)),
               death_in_hospital = case_when(
               DTHHRDY %in% c(0,3,4) ~ TRUE,
               DTHHRDY %in% c(1,2) ~ FALSE))
        })
analysis_out <- NULL
for (cur_ind in seq(nrow(tissues_with_clusters))) {
    cur_tiss <- tissues_with_clusters$tissue[cur_ind]
    cur_clust <- tissues_with_clusters$cluster[cur_ind]
    if (cur_clust == "X") {
        next()
    }
    cur_dat <- profile_list[[cur_tiss]]
    model_formula <- paste0(cur_clust,
                            " ~ death_in_hospital + SMTSISCH + SEX + AGE")
    temp_model <- lm(as.formula(model_formula),data = cur_dat)
    new_rows <- cbind(cur_tiss,broom::tidy(temp_model))
    analysis_out <- rbind(analysis_out, new_rows)
}
write.csv(analysis_out, "data_out/single_tissue_MT_hospital_models.csv",row.names = F)


## Death in hospital sig?
analysis_out %>% mutate(padj = p.adjust(p.value,method = "BH"),
                        is_sig = padj <= 0.05) %>%
    filter(startsWith(term, "death"))

```

