---
title: "General meta-cluster stats"
author: "Tim N"
date: "12/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(viridis)
library(patchwork)
library(ggforce)
source("../../global_in/general_scripts.R")
```

```{r}
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
manual_curation <- read.csv("../../manual_cluster_analysis/manual_curation.csv")
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv") %>%
    mutate(DTHHRDY_factor = factor(DTHHRDY, levels = c(1,2,3,4,0)),
           DTHHRDY_ordinal = factor(DTHHRDY, levels = c(1,2,3,4,0),ordered = TRUE))
           
samp_dat <- data.table::fread("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```


Master overlaps
```{r}
master_overlap <- ClusterGeneOverlaps(c("FOSB", "IL6", "CHI3L1"),cluster_list) %>%
    rownames_to_column("cluster") %>%
    ## remove x cluster
    filter(!str_detect(cluster, "X")) %>%
    mutate(gene_overlaps = case_when(
        grepl("IL6.*FOSB", found_genes) ~ "IL6 and FOSB",
        grepl("IL6.*CHI3L1", found_genes) ~ "IL6 and CHI3L1",
        grepl("CHI3L1*FOSB", found_genes) ~ "CHI3L1 and FOSB",
        grepl("IL6.*FOSB.*CHI", found_genes) ~ "IL6, FOSB, and CHI3L1",
        TRUE ~ found_genes
        ))

table(master_overlap$gene_overlaps)
```


FOSB analysis

```{r}
### How frequently is FOSB variable
CommonGenes("FOSB", cluster_list, x_clust = T,1)
### How frequentyly does FOSB cluster
CommonGenes("FOSB", cluster_list, x_clust = F,1)
### FOSB's top 10 most common clustering genes
CommonGenes("FOSB", cluster_list, x_clust = F,11)

cat(CommonGenes("FOSB", cluster_list, x_clust = F,11)$final_vect, sep = "\n")
```

IL6 over SELE

```{r}
### How frequently is IL6 variable
CommonGenes("IL6", cluster_list, x_clust = T,1)
### How frequently is SELE variable
CommonGenes("SELE", cluster_list, x_clust = T,1)

### How frequentyly does IL6 cluster
CommonGenes("IL6", cluster_list, x_clust = F,1)
### How frequentyly does SELE cluster
CommonGenes("SELE", cluster_list, x_clust = F,1)

### IL6's top 10 most common clustering genes
common_IL6 <- CommonGenes("IL6", cluster_list, x_clust = F,11)
common_IL6
### SELE's top 10 most common clustering genes
common_SELE <- CommonGenes("SELE", cluster_list, x_clust = F,11)
common_SELE

cat(intersect(common_IL6$final_vect, common_SELE$final_vect), sep = "\n")

```

PLA2G2A should be replaced wuth CHI3L1
```{r}
### How frequently is IL6 variable
CommonGenes("CHI3L1", cluster_list, x_clust = T,1)
### How frequently is SELE variable
CommonGenes("PLA2G2A", cluster_list, x_clust = T,1)

### How frequentyly does IL6 cluster
CommonGenes("CHI3L1", cluster_list, x_clust = F,1)
### How frequentyly does SELE cluster
CommonGenes("PLA2G2A", cluster_list, x_clust = F,1)

### IL6's top 10 most common clustering genes
common_chi3l1 <- CommonGenes("CHI3L1", cluster_list, x_clust = F,11)
common_chi3l1
### SELE's top 10 most common clustering genes
common_pla2g2a <- CommonGenes("PLA2G2A", cluster_list, x_clust = F,11)
common_pla2g2a

cat(intersect(common_chi3l1$final_vect, common_pla2g2a$final_vect))
```

Generate plots for all clusters, mark whether the have any of the following
cluster markers:
FOSB; HBB; PLA2G2A; CHI3L1; IL6; SELE
```{r}
marker_genes <- c("FOSB", "HBB", "CHI3L1", "IL6", "SELE", "PLA2G2A")
clusters_of_interest <- ClusterGeneOverlaps(marker_genes,cluster_list) %>%
    rownames_to_column("cluster") %>%
    ## remove x cluster
    filter(!str_detect(cluster, "X")) %>%
    separate(., "cluster",into = c("r_names", "cluster"),sep = "-") %>%
    left_join(., key_dat)

zscores_of_tiss <- ZscoreProfilePuller(
    r_name_vect = unique(clusters_of_interest$r_names),
    "../../MARCC output/variance_profiles_kendall/")

### Begin loop of data
master_plot_list <- list()
full_results <- list()
analysis_out <- NULL
for (clust_ind in seq(nrow(clusters_of_interest))) {
    cur_clust <- clusters_of_interest[clust_ind,]
    temp_df <- zscores_of_tiss[[cur_clust$r_names]][,
                                                    c("SUBJID",
                                                      "SAMPID",
                                                      cur_clust$cluster)]
    temp_df <- left_join(temp_df, phen_dat, by = "SUBJID") %>%
        left_join(., samp_dat, by = "SAMPID")
    
    ### Plotting data
    isch_plot <- ggplot(temp_df, aes_string(x = "SMTSISCH",
                               y = cur_clust$cluster,
                               color = "DTHHRDY_factor")) +
        geom_point() +
        scale_color_viridis(option = "C", discrete = T,end = .90) +
        theme_classic() +
        labs(title = cur_clust$r_names, subtitle = cur_clust$found_genes)
    hardy_plot <- ggplot(temp_df, aes_string(x = "DTHHRDY_factor",
                               y = cur_clust$cluster,
                               color = "DTHHRDY_factor")) +
        geom_sina() +
        scale_color_viridis(option = "C", discrete = T,end = .90) +
        theme_classic() #+
        #labs(title = cur_clust$r_names, subtitle = cur_clust$found_genes)
    ## Joining plots
    patch_plot <- isch_plot / hardy_plot +
        plot_layout(guides = "collect") & theme(legend.position = "right")
    master_plot_list[[paste0(cur_clust$r_names,"_",cur_clust$cluster)]] <-
        patch_plot
    ### Statistical analysis
    temp_formula <- paste0(cur_clust$cluster,
                           " ~ DTHHRDY_ordinal + SMTSISCH + AGE + SEX + SMGEBTCH")
    tidy_res <- lm(as.formula(temp_formula),data = temp_df) %>% broom::tidy()
    tidy_res$tissue <- cur_clust$r_names
    tidy_res$cluster <- cur_clust$cluster
    tidy_res$genes <- cur_clust$found_genes
    ## Save all data in list
    full_results[[paste0(cur_clust$r_names,"_",cur_clust$cluster)]] <- tidy_res
    ## Filter data for p-value correction on ischemic time and hardy
    ## the variables we care about. Also remove blood only because that is jsut
    ## a positive control
    tidy_filt <- tidy_res %>% filter(grepl("factor|SMTSISCH|ordinal.L",
                                           x = term), genes != "HBB")
    analysis_out <- rbind(analysis_out, tidy_filt)
}

## Print all plots
pdf("data_out/possible_isch_hardy_clusters.pdf", height = 9, width = 9)
for (cur_plot in master_plot_list) {
    print(cur_plot)
}
dev.off()

## Correct for multiple correction
analysis_out <- mutate(analysis_out,
                       p_adj = p.adjust(p.value, method = "fdr"),
                       is_sig = p_adj < 0.05,
                       positive_o_neg = ifelse(estimate > 0,
                                               "positive",
                                               "negative"),
                       has_IL6 = ifelse(str_detect(genes, "IL6"),
                                           "yes", "no"),
                       has_PLA2G2A = ifelse(str_detect(genes, "PLA2G2A"),
                                           "yes", "no"),
                       has_CHI3L1 = ifelse(str_detect(genes, "CHI3L1"),
                                           "yes", "no"),
                       has_SELE = ifelse(str_detect(genes, "SELE"),
                                           "yes", "no"),
                       has_FOSB = ifelse(str_detect(genes, "FOSB"),
                                           "yes", "no"))

table(analysis_out$is_sig, analysis_out$term)

hardy_result <- filter(analysis_out,
                           str_detect(term, "DTHHRDY"))


sig_hardy_result <- filter(analysis_out,
                           str_detect(term, "DTHHRDY"),
                           is_sig == TRUE)



table(sig_hardy_result$positive_o_neg, sig_hardy_result$has_IL6)
table(sig_hardy_result$positive_o_neg, sig_hardy_result$has_SELE)
table(sig_hardy_result$positive_o_neg, sig_hardy_result$has_PLA2G2A)
table(sig_hardy_result$positive_o_neg, sig_hardy_result$has_CHI3L1)
table(sig_hardy_result$positive_o_neg, sig_hardy_result$has_FOSB)

## Rsplit brains
brain_ind <- str_detect(sig_hardy_result$tissue, "brain")
sig_hardy_result_no_brain <- sig_hardy_result[!brain_ind,]
sig_hardy_result_brain <- sig_hardy_result[brain_ind,]


table(sig_hardy_result_no_brain$positive_o_neg, sig_hardy_result_no_brain$has_IL6)
table(sig_hardy_result_no_brain$positive_o_neg, sig_hardy_result_no_brain$has_CHI3L1)
table(sig_hardy_result_no_brain$positive_o_neg, sig_hardy_result_no_brain$has_PLA2G2A)

```

Upset plots
All Clusters
```{r}
require(UpSetR)
upset_genes <- c("SELE", "IL6",  "FOSB", "PLA2G2A", "CHI3L1")
upset_list <- list()
for (cur_upset_gene in upset_genes) {
    upset_list[[cur_upset_gene]] <- which(str_detect(hardy_result$genes, cur_upset_gene))
}
upset(fromList(upset_list), order.by = "freq",text.scale = 1.2)
```

Sig clusters
```{r}
sig_upset_list <- list()
for (cur_upset_gene in upset_genes) {
    sig_upset_list[[cur_upset_gene]] <- which(str_detect(sig_hardy_result$genes, cur_upset_gene))
}
upset(fromList(sig_upset_list), order.by = "freq",text.scale = 1.3)
```
Brain clusters
```{r}
brain_upset_list <- list()
for (cur_upset_gene in upset_genes) {
    brain_upset_list[[cur_upset_gene]] <- which(str_detect(sig_hardy_result_brain$genes, cur_upset_gene))
}
upset(fromList(brain_upset_list), order.by = "freq",text.scale = 1.4)
```

No Brain
```{r}
no_brain_upset_list <- list()
for (cur_upset_gene in upset_genes) {
    no_brain_upset_list[[cur_upset_gene]] <- which(str_detect(sig_hardy_result_no_brain$genes, cur_upset_gene))
}
upset(fromList(no_brain_upset_list), order.by = "freq",text.scale = 1.4)
```

