---
title: "figure_4c_d"
author: "Tim N"
date: "12/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DESeq2)
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
source("../../global_in/general_scripts.R")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv") %>%
    mutate(Race_Character = case_when(
        RACE == 1 ~ "Asian",
        RACE == 2 ~ "Black or African American",
        RACE == 3 ~ "White", 
        RACE == 4 ~ "American Indian or Alaska Native",
        RACE == 98 ~ "Not Reported",
        RACE == 99 ~ "Unknown"
    ))

tissue_list = c("lung",
                "artery_coronary",
                "kidney_cortex",
                "skin_sun_exposed__lower_leg",
                "prostate",
                "brain_spinal_cord__cervical_c_1",
                "brain_putamen__basal_ganglia",
                "colon_sigmoid",
                "whole_blood",
                "adipose_subcutaneous",
                "adipose_visceral__omentum",
                "artery_aorta",
                "artery_tibial",
                "artery_coronary",
                "breast_mammary_tissue",
                "adrenal_gland",
                "colon_transverse",
                "minor_salivary_gland",
                "skin_not_sun_exposed__suprapubic",
                "nerve_tibial",
                "liver",
                "stomach",  
                "small_intestine_terminal_ileum",
                "heart_atrial_appendage",
                "spleen",
                "pancreas",
                "pituitary",
                "heart_left_ventricle",
                "testis",
                "esophagus_gastroesophageal_junction",
                "esophagus_mucosa",
                "esophagus_muscularis",
                "ovary",
                "uterus",
                "vagina")
```


```{r}
dat <- GenesFromTissues(tiss_of_int = "",
                       genes_of_int = c("GSTM1", "MTND1P23", "C21orf33"),
                       vst_location = "../../Setup Code/output/",
                       run_all_available = T,
                       key_dat = key_dat) %>%
    filter(tissue %in% tissue_list)
```

Start with adipose
```{r}

all_dat <- left_join(dat, phen_dat) %>%
    filter(Race_Character != "Unknown") %>%
    mutate(above_GSTM_thresh = GSTM1 > 6.2,
           above_MTND_thresh = MTND1P23 > 10,
           above_C21_thresh = C21orf33 > 6.2,)


gstm_table <- table(all_dat$above_GSTM_thresh, all_dat$Race_Character) %>%
    as.data.frame()
gstm_freqs <- gstm_table$Freq
top = 13.2
bot = 2.8

ggplot(all_dat, aes(Race_Character, GSTM1, color = Race_Character)) +
    ggforce::geom_sina() +
    annotate("text",
             y = c(bot, top,
                  bot, top,
                  bot, top,
                  bot, top),
             x= c(1.2, 1.2,
                  2.2, 2.2,
                  3.2, 3.2,
                  4.2, 4.2),
             label = c(gstm_freqs[1], gstm_freqs[2],
                       gstm_freqs[3], gstm_freqs[4],
                       gstm_freqs[5],gstm_freqs[6],
                       gstm_freqs[7],gstm_freqs[8])) +
    scale_color_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    geom_hline(yintercept = 6.2) +
    theme_bw() +
    theme(legend.position = "none")
ggsave("figure_out/figure_4c.pdf", height = 5, width = 6)
```
Collapsed GSTM
```{r}
gstm_med <- all_dat %>% group_by(SUBJID) %>%
    summarize(med_gstm1 = median(GSTM1)) %>%
    mutate(above_GSTM_thresh = med_gstm1 > 6.2) %>%
    left_join(phen_dat)

gstm_table <- table(gstm_med$above_GSTM_thresh, gstm_med$Race_Character) %>%
    as.data.frame()
gstm_freqs <- gstm_table$Freq
top = 13.2
bot = 2.8


ggplot(gstm_med, aes(Race_Character, med_gstm1, color = Race_Character)) +
    ggforce::geom_sina()+
    annotate("text",
             y = c(bot, top,
                  bot, top,
                  bot, top,
                  bot, top),
             x= c(1.2, 1.2,
                  2.2, 2.2,
                  3.2, 3.2,
                  4.2, 4.2),
             label = c(gstm_freqs[1], gstm_freqs[2],
                       gstm_freqs[3], gstm_freqs[4],
                       gstm_freqs[5],gstm_freqs[6],
                       gstm_freqs[7],gstm_freqs[8])) +
    scale_color_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    geom_hline(yintercept = 6.2) +
    theme_bw() +
    theme(legend.position = "none")
ggsave("figure_out/figure_4c_v2.pdf", height = 5, width = 6)
```


```{r}

mt_table <- table(all_dat$above_MTND_thresh, all_dat$Race_Character) %>%
    as.data.frame()
mt_freqs <- mt_table$Freq
top = 17
bot = 4
ggplot(all_dat, aes(Race_Character, MTND1P23, color = Race_Character)) +
    ggforce::geom_sina() +
    annotate("text",
             y = c(bot, top,
                  bot, top,
                  bot, top,
                  bot, top),
             x= c(1.2, 1.2,
                  2.2, 2.2,
                  3.2, 3.2,
                  4.2, 4.2),
             label = c(mt_freqs[1], mt_freqs[2],
                       mt_freqs[3], mt_freqs[4],
                       mt_freqs[5], mt_freqs[6],
                       mt_freqs[7], mt_freqs[8])) +
    scale_color_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    geom_hline(yintercept = 10) +
    theme_bw() +
    theme(legend.position = "none")

ggsave("figure_out/figure_4d.pdf", height = 5, width = 6)

```

```{r}
med_mito <- all_dat %>% group_by(SUBJID) %>%
    summarize(med_mt = median(MTND1P23)) %>%
    mutate(above_MTND_thresh = med_mt > 10) %>%
    left_join(phen_dat)


mt_table <- table(med_mito$above_MTND_thresh, med_mito$Race_Character) %>%
    as.data.frame()
mt_freqs <- mt_table$Freq
top = 17
bot = 4

ggplot(med_mito, aes(Race_Character, med_mt, color = Race_Character)) +
    geom_sina()+
    scale_color_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    geom_hline(yintercept = 10) +
    theme_bw() +
    theme(legend.position = "none") +
    annotate("text",
             y = c(bot, top,
                  bot, top,
                  bot, top,
                  bot, top),
             x= c(1.2, 1.2,
                  2.2, 2.2,
                  3.2, 3.2,
                  4.2, 4.2),
             label = c(mt_freqs[1], mt_freqs[2],
                       mt_freqs[3], mt_freqs[4],
                       mt_freqs[5], mt_freqs[6],
                       mt_freqs[7], mt_freqs[8]))

ggsave("figure_out/figure_4d_v2.pdf", height = 5, width = 6)
```


Fisher's Exact V1
```{r}
mtnd_result <- fisher.test(all_dat$above_MTND_thresh, all_dat$Race_Character)
mtnd_result$p.value

c21_result <- fisher.test(all_dat$above_C21_thresh, all_dat$Race_Character)
c21_result$p.value
```

Fisher's Exact V2
```{r}
med_C21 <- all_dat %>% group_by(SUBJID) %>%
    summarize(med_C21 = median(C21orf33)) %>%
    mutate(above_C21_thresh = med_C21 > 6.2) %>%
    left_join(phen_dat)


mtnd_result <- fisher.test(med_mito$above_MTND_thresh, med_mito$Race_Character)
mtnd_result$p.value

c21_result <- fisher.test(med_C21$above_C21_thresh, med_C21$Race_Character)
c21_result$p.value
```


## Update 28-06-23
Reviewers requested a change in the plotting to a histogram and to use all samples, even if they're from the same patient

```{r}
ggplot(all_dat, aes(Race_Character, GSTM1, color = Race_Character)) +
    ggforce::geom_sina() +
    annotate("text",
             y = c(bot, top,
                  bot, top,
                  bot, top,
                  bot, top),
             x= c(1.2, 1.2,
                  2.2, 2.2,
                  3.2, 3.2,
                  4.2, 4.2),
             label = c(gstm_freqs[1], gstm_freqs[2],
                       gstm_freqs[3], gstm_freqs[4],
                       gstm_freqs[5],gstm_freqs[6],
                       gstm_freqs[7],gstm_freqs[8])) +
    scale_color_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    geom_hline(yintercept = 6.2) +
    theme_bw() +
    theme(legend.position = "none")

ggplot(all_dat, aes(GSTM1, fill = Race_Character)) +
    geom_density() +
    coord_flip() +
    scale_fill_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    theme_bw() +
    theme(legend.position = "none") +
    facet_wrap(~Race_Character, nrow = 1)
ggsave(filename = "figure_out/figure_4c_density_flip.pdf", height = 5, width = 6.5)


ggplot(all_dat, aes(GSTM1, fill = Race_Character)) +
    geom_density() +
    scale_fill_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    theme_bw() +
    theme(legend.position = "none") +
    facet_wrap(~Race_Character, ncol = 1)
ggsave(filename = "figure_out/figure_4c_density.pdf", height = 7, width = 5)
```

```{r}
ggplot(all_dat, aes(MTND1P23, fill = Race_Character)) +
    geom_density() +
    scale_fill_manual(values=c("#a9449a", "#33b449", "#015794", "#c72827")) +
    theme_bw() +
    theme(legend.position = "none") +
    facet_wrap(~Race_Character, ncol = 1)
ggsave(filename = "figure_out/figure_4d_density.pdf", height = 7, width = 5)

```
```{r}
table(all_dat$Race_Character)
```

