---
title: "Ovary analysis"
author: "Tim N"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


libraries
```{r}
library(tidyverse)
library(pheatmap)
source("../../global_in/general_scripts.R")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
```
Read in ovary excel sheet
```{r}
all_marker_genes <- readxl::read_excel("data_in/41467_2020_14936_MOESM2_ESM.xlsx",
                   sheet = 2,skip = 2)

all_marker_genes <- filter(all_marker_genes,p_val_adj < 0.05)
marker_gene_table <- table(all_marker_genes$gene)
unique_markers <- names(marker_gene_table)[marker_gene_table == 1]
all_marker_genes <- filter(all_marker_genes, gene %in% unique_markers)
```
Load in clusters
```{r}
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/",x_clust = F)
ovary_dat <- cluster_list$ovary
```

Calculate overlaps
```{r}
all_marker_genes <- mutate(all_marker_genes, cluster_factor = factor(cluster))
dat_out <- NULL
for (cluster_ind in seq_along(ovary_dat)) {
    cur_genes <- ovary_dat[[cluster_ind]]
    temp_dat <- filter(all_marker_genes, gene %in% cur_genes)
    new_row <-t(cbind(table(temp_dat$cluster_factor))) %>%
        as.data.frame() %>%
        cbind(.,paste0(cur_genes,collapse = ";"))
    rownames(new_row) <- names(ovary_dat)[cluster_ind]
    dat_out <- rbind(dat_out,new_row)
}
```


```{r}

ovary_profile <- ZscoreProfilePuller("ovary", "../../MARCC output/variance_profiles_kendall/")
## Get a correlation matrix of esophagus clusters
all_cor_mat <- ClusterCombinerZscores("ovary",
                       cluster_vect = colnames(ovary_profile$ovary)[-1:-2],
                       ovary_profile,cor_matrix = T)
## Cluster and plot these results to get a clear understanding of esophagus
## relationships
dendo <- hclust(dist(1-abs(all_cor_mat)))
pheatmap((all_cor_mat),cluster_cols = dendo, cluster_rows = FALSE)
pheatmap((all_cor_mat),cluster_cols = dendo, cluster_rows = dendo)
```
B.2 C.2 H F
B.1 C.1 K
F G




```{r}
mega_cluster_1 <- c("B.2", "C.2", "H", "F")
ClusterCombinerZscores("ovary",
                       cluster_vect = c("B.2", "C.2", "H", "F"),
                       ovary_profile,cor_matrix = T)
mega_cluster_genes <- ClusterCombinerGenes("ovary", mega_cluster_1, cluster_list,for_R = T)
mega_cluster_1_marker <- filter(all_marker_genes, gene %in% mega_cluster_genes)
table(mega_cluster_1_marker$cluster_factor)
## Oocyte and granulosa cells
```

```{r}
mega_cluster_2 <- c("B.1", "C.1", "K")
ClusterCombinerZscores("ovary",
                       cluster_vect = mega_cluster_2,
                       ovary_profile,cor_matrix = T)
mega_cluster_2_genes <- ClusterCombinerGenes("ovary", mega_cluster_2, cluster_list, T)
mega_cluster_2_marker <- filter(all_marker_genes, gene %in% mega_cluster_2_genes)
table(mega_cluster_2_marker$cluster_factor)
```

Phenotype analysis
```{r}
ovary_df <- ovary_profile$ovary
ovary_df$mega_z_1 <- ClusterCombinerZscores("ovary",
                       cluster_vect = mega_cluster_1,
                       ovary_profile,cor_matrix = F)

ovary_df$mega_z_2 <- ClusterCombinerZscores("ovary",
                       cluster_vect = mega_cluster_2,
                       ovary_profile,cor_matrix = F)

plot(ovary_df$mega_z_1, ovary_df$mega_z_2)


ovary_df <- left_join(ovary_df, phen_dat) %>%
    mutate(DTHHRDY_factor = factor(DTHHRDY, c(1,2,3,4,0)))

ggplot(ovary_df, aes(AGE, mega_z_1, color = DTHHRDY_factor)) +
    geom_point()

ggplot(ovary_df, aes(AGE, mega_z_2, color = DTHHRDY_factor)) +
    geom_point()



ggplot(ovary_df, aes(DTHHRDY_factor, mega_z_2, color = DTHHRDY_factor)) +
    ggforce::geom_sina()

ggplot(ovary_df, aes(TRISCHD, mega_z_2)) +
    geom_point()

mega_z_2_model <- lm(mega_z_2 ~ AGE + TRISCHD, data = ovary_df) 
summary(mega_z_2_model)

mega_z_1_model <- lm(mega_z_1 ~ AGE + TRISCHD, data = ovary_df) 
summary(mega_z_1_model)

### No plag
ovary_df$mega_z_2_noplag <- ClusterCombinerZscores("ovary",
                       cluster_vect = c("B.1", "K"),
                       ovary_profile,cor_matrix = F)
mega_z_2_noplag_model <- lm(mega_z_2_noplag ~ AGE + DTHHRDY + TRISCHD, data = ovary_df) 
summary(mega_z_2_noplag_model)

ggplot(ovary_df, aes(AGE, mega_z_2_noplag, color = DTHHRDY_factor)) +
    geom_point()
mega_cluster_2_noplag_genes <- ClusterCombinerGenes("ovary",  c("B.1", "K"), cluster_list, T)
mega_cluster_2_noplag_marker <- filter(all_marker_genes, gene %in% mega_cluster_2_noplag_genes)
table(mega_cluster_2_noplag_marker$cluster_factor)
```

