---
title: "Understanding mitochondria genes"
author: "Tim N"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(lme4)
library(lmerTest)
source("../../global_in/general_scripts.R")
```

```{r}
cluster_list <- AllGeneClusterPuller("../../MARCC output/variance_genes_kendall/")
manual_curation <- read.csv("../../manual_cluster_analysis/manual_curation.csv")
key_dat <- read.csv("../../automated_cluster_analysis/data_out/key_table.csv")
phen_dat <- read.csv("../../global_in/gtex_phenotypes_v8.csv")
samp_dat <- data.table::fread("../../global_in/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```


```{r}
cluster_mito <- c("MTCO3P12",
"MTCO1P12",
"MTND1P23",
"MTND2P28",
"MT−TS1",
"MTND4P12",
"MT−TE",
"MTATP8P1",
"MTCO2P12",
"MT−TY",
"MT−TL2",
"MT−TP")
```



Load a brain z-score with mitochondrial genes
```{r}
brain_profs <- ZscoreProfilePuller(r_name_vect =  c("brain_cerebellum",
                                                    "brain_cortex",
                                                    "brain_substantia_nigra"),
                                   location = "../../MARCC output/variance_profiles_kendall/")
cereb_mito <- brain_profs$brain_cerebellum %>% select(SUBJID, cereb_samp = SAMPID, cereb_mito = A)
cereb_samp <- brain_profs$brain_cerebellum %>% select(SUBJID, SAMPID, cereb_mito = A)
cortex_mito <- brain_profs$brain_cortex %>% select(SUBJID,corex_sam = SAMPID, cortex_mito = A)
cortex_samp <- brain_profs$brain_cortex %>% select(SUBJID, SAMPID, cortex_mito = A)

join_brain <- left_join(cereb_mito,cortex_mito)%>%
    left_join(.,phen_dat)


join_brain %>%
    ggplot(., aes(cereb_mito, cortex_mito)) +
    geom_point() 

join_brain %>%
    ggplot(., aes(factor(COHORT), cortex_mito)) +
    ggforce::geom_sina()

join_brain %>%
    ggplot(., aes((DTHRFGD), cortex_mito)) +
    geom_point()
```


```{r}
cereb_samp <- left_join(cereb_samp,phen_dat) %>% left_join(., samp_dat) %>%
    mutate(SMGEBTCHD = as.Date(SMGEBTCHD,format = "%m/%d/%Y"))
cortex_samp<- left_join(cortex_samp,phen_dat) %>% left_join(., samp_dat)
ggplot(cereb_samp, aes(factor(SMGEBTCHT), cereb_mito)) +
    ggforce::geom_sina()

ggplot(cortex_samp, aes(SMRIN, cortex_mito)) +
    geom_point()


summary(lm(cereb_mito ~ SMRIN + SMGNSDTC, data = cereb_samp))
```
Test if mito is all RIN
```{r}
## Get all brain mito clusters labeled
clusters_to_pull <- NULL
for (tiss_ind in seq_along(cluster_list)) {
    current_tiss <- names(cluster_list)[tiss_ind]
    if (!str_detect(current_tiss, "brain")) {
        next()
    }
    current_tiss_clust <- cluster_list[[tiss_ind]]
    for (cluster_ind in seq_along(current_tiss_clust)) {
        cluster_name <- names(current_tiss_clust)[cluster_ind]
        cur_genes <- current_tiss_clust[[cluster_ind]]
        if (cluster_name == "X") {
            next()
        }
        if (any(cluster_mito %in% cur_genes)) {
            clusters_to_pull<- rbind(clusters_to_pull,
                                     cbind(current_tiss,cluster_name))
        }
        
    }
}

## Pull said clusters
profs_mito <- ZscoreProfilePuller(r_name_vect = clusters_to_pull[,1],
                                  "../../MARCC output/variance_profiles_kendall/")

for_model <- NULL

for (row_ind in seq(nrow(clusters_to_pull))) {
    current_df <- profs_mito[[clusters_to_pull[row_ind,1]]]
    new_rows <- cbind(current_df[,c("SUBJID", "SAMPID", clusters_to_pull[row_ind,2])],
             clusters_to_pull[row_ind,1])
    colnames(new_rows) <- c("SUBJID", "SAMPID", "mito_cluster", "tissue")
    for_model <- rbind(for_model, new_rows)
}

## Generalized linear model
for_model <- left_join(for_model, samp_dat) %>%
    left_join(.,phen_dat)

simple_model <- model_out <- lmer(mito_cluster ~ SMRIN + (1|tissue) + (1|SUBJID), data = for_model)

model_out <- lmer(mito_cluster ~ SMRIN + SMTSISCH + SEX + AGE + (1|tissue) + (1|SUBJID), data = for_model)
summary(model_out)

anova(simple_model, model_out)

## Creat obscene model and scale the values
pre_norm_dat <- select(for_model, starts_with("SM")) %>%
    select_if(~ !any(is.na(.))) %>%
    select_if(is.numeric)

pre_norm_dat <- pre_norm_dat[, sapply(pre_norm_dat, function(col) length(unique(col))) > 1]
pre_norm_dat_cent <- sweep(pre_norm_dat,2,colMeans(pre_norm_dat))
pre_join_norm_dat <- sweep(pre_norm_dat_cent,2, apply(pre_norm_dat_cent,2,sd),FUN = "/")

pre_obscene <- for_model %>% select(mito_cluster, SUBJID, SAMPID, tissue, SEX, AGE)
obscene_dat <- cbind(pre_obscene, pre_join_norm_dat)

covariates <- colnames(obscene_dat)[-1:-4]
obscene_formula <- ((paste0("mito_cluster ~",paste0(covariates,
                                            collapse = " + "), " + (1|tissue) + (1|SUBJID)")))

obscene_model <- lmer(as.formula(obscene_formula), data = obscene_dat)
obscene_summary <- summary(obscene_model)

original_model <- lmer(mito_cluster ~ SMRIN + SMTSISCH + SEX + AGE + (1|tissue) + (1|SUBJID), data = obscene_dat)

anova(original_model, obscene_model)

View(obscene_summary$coefficients)

## Include PH and batch for final model
obscene_dat_plus <- left_join(obscene_dat, select(for_model, SAMPID, MHBRNPH, SMNABTCH))
obscene_dat_formula_plus <- ((paste0("mito_cluster ~",paste0(covariates,
                                            collapse = " + "), "+ MHBRNPH + SMNABTCH + (1|tissue) + (1|SUBJID)"))) 
obscene_model_plus <- lmer(as.formula(obscene_dat_formula_plus), data = obscene_dat_plus)
obscene_model_summary <- summary(obscene_model_plus)

tidy_with_intron_model <- broom.mixed::tidy(obscene_model_plus)

## Remove intergenic variables SMSPLTRD and SMNTERRT as mitochondria genes lack
## introns so this is a dog wagging the tail situation
no_intron_formula <- str_replace(obscene_dat_formula_plus, "[+] SMSPLTRD [+]","+")
no_intron_formula <- str_replace(no_intron_formula, "[+] SMNTERRT [+]","+")



obscene_model_no_intron <- lmer(as.formula(no_intron_formula), data = obscene_dat_plus)

no_intron_summary <- summary(obscene_model_no_intron)

tidy_final_model <- broom.mixed::tidy(obscene_model_no_intron)

### Plotting

ggplot(obscene_dat, aes(SMSPLTRD, mito_cluster, color = tissue)) +
    geom_point(alpha = .5) +
    theme_classic() +
    theme(legend.position = "bottom")

ggplot(obscene_dat, aes(SMRIN, mito_cluster, color = tissue)) +
    geom_point(alpha = .5) +
    theme_classic() +
    theme(legend.position = "bottom")

ggplot(obscene_dat, aes(SMSPLTRD, SMRIN, color = tissue)) +
    geom_point(alpha = .5) +
    theme_classic() +
    theme(legend.position = "bottom")
```

Make sure SMSPLTRD isn't associated with a factor
```{r}
SMSPLTRD_model_out <- lmer(SMSPLTRD ~  + SMNABTCH + SMNABTCHD + SMGEBTCH + SMCENTER  + (1|tissue) + (1|SUBJID), data = for_model)

SMSPLTRD_summary <- summary(SMSPLTRD_model_out)

```




